const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright-core');
const fs=require('fs');const http=require('http');const assert=require('assert/strict');
const root=require('path').resolve(__dirname, '../www');
const wav=Buffer.alloc(44+8000*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(16000,40);
const server=http.createServer((q,r)=>{if(q.url==='/tone.wav'){r.setHeader('Content-Type','audio/wav');return r.end(wav)}let p=root+q.url.split('?')[0];try{r.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':'text/html');r.end(fs.readFileSync(p))}catch{r.statusCode=404;r.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_PATH,headless:true});try{
for(const version of ['1.11.5','2.3.3'])for(const sound of [false,true])for(const webgl of [false,true]){
 const page=await browser.newPage({hasTouch:true,viewport:{width:360,height:640}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let code=sound?(version==='2.3.3'?`let song; async function setup(){createCanvas(120,80); song=await loadSound('/tone.wav'); window.loaded=!!song.play;}`:`let song; function preload(){song=loadSound('/tone.wav')} function setup(){createCanvas(120,80);window.loaded=!!song.play;}`):`function setup(){createCanvas(120,80);background(80);window.loaded=true;}`;
 code=code.replaceAll('createCanvas(120,80)',webgl?'createCanvas(120,80,WEBGL)':'createCanvas(120,80)');
 await page.addInitScript(({version,sound,code})=>{window.statuses=[];window.errors=[];window.Android={getP5Version:()=>version,isP5SoundEnabled:()=>sound,getSketchCode:()=>code,onStatusChanged:s=>statuses.push(s),onError:e=>errors.push(e),onRuntimeError:e=>errors.push(e)}} ,{version,sound,code});
 await page.goto('http://127.0.0.1:'+server.address().port+'/p5_runner.html');
 try{await page.waitForFunction(()=>window.loaded&&statuses.includes('実行中'),{},{timeout:10000});if(sound){assert.equal(await page.locator('#sound-start').count(),0);const initialCanvas=await page.locator('canvas').boundingBox();await page.touchscreen.tap(initialCanvas.x+initialCanvas.width/2,initialCanvas.y+initialCanvas.height/2);await page.waitForFunction(()=>getAudioContext().state==='running');await page.evaluate(()=>pauseSketch());await page.waitForFunction(()=>getAudioContext().state==='suspended');await page.evaluate(()=>resumeSketch());await page.waitForFunction(()=>getAudioContext().state==='running');}if(sound) await page.evaluate(()=>{song.play();if(!song.isPlaying())throw new Error('Sound playback did not start');song.stop();const oscillator=new p5.Oscillator();const fft=new p5.FFT();oscillator.start();fft.analyze();oscillator.stop();});
 for(const size of [{width:360,height:640},{width:960,height:540},{width:360,height:640}]){await page.setViewportSize(size);await page.waitForTimeout(100);const box=await page.locator('canvas').boundingBox();await page.touchscreen.tap(box.x+box.width*.75,box.y+box.height*.25);const position=await page.evaluate(()=>({x:mouseX,y:mouseY}));assert.ok(Math.abs(position.x-90)<2,JSON.stringify(position));assert.ok(Math.abs(position.y-20)<2,JSON.stringify(position));}
 assert.deepEqual(await page.evaluate(()=>window.errors),[]);assert.deepEqual(errors,[]);console.log('PASS',version,sound,webgl?'WEBGL':'2D')}catch(e){console.log('FAIL',version,sound,await page.evaluate(()=>({errors:window.errors,statuses,loaded:window.loaded})),errors,e.message);process.exitCode=1}await page.close();
}
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
