package com.hikariatelier.app

internal fun resolveUiLanguage(selection: String, deviceLanguage: String): String {
    val language = if (selection == "system") deviceLanguage.lowercase().substringBefore('-').substringBefore('_') else selection
    return if (language in setOf("ja", "en", "zh")) language else "en"
}

internal fun translateUi(source: String, language: String): String {
    if (language == "ja") return source
    val entry = uiTranslations[source] ?: return source
    return if (language == "zh") entry.second else entry.first
}

internal val uiTranslations = mapOf(
    "p5.jsアカウント" to ("p5.js account" to "p5.js 账户"),
    "p5.js Web Editor" to ("p5.js Web Editor" to "p5.js Web Editor"),
    "p5.js Web Editorのユーザー名から公開作品を取り込みます。パスワードは使用しません。" to ("Import public sketches by p5.js Web Editor username. Your password is never used." to "通过 p5.js Web Editor 用户名导入公开作品，不使用密码。"),
    "ユーザー名" to ("Username" to "用户名"),
    "作品を取得" to ("Load works" to "获取作品"),
    "ユーザー名を入力して公開作品を取得してください" to ("Enter a username to load public works" to "输入用户名以获取公开作品"),
    "%s件の公開作品" to ("%s public works" to "%s 个公开作品"),
    "タップして取り込む" to ("Tap to import" to "点击导入"),
    "公開作品がありません" to ("No public works found" to "没有公开作品"),
    "p5.jsの作品を取得できませんでした" to ("Could not load p5.js works" to "无法获取 p5.js 作品"),
    "作品を取り込めませんでした。ファイル数・容量・通信環境を確認してください" to ("Could not import the work. Check its files, size, and your connection." to "无法导入作品，请检查文件数量、容量和网络连接。"),
    "p5.jsの作品を取り込みました" to ("p5.js work imported" to "已导入 p5.js 作品"),
    "アカウントの公開作品を選んで取り込みます" to ("Choose and import a public work from an account" to "从账户中选择并导入公开作品"),
    "p5.jsから作品を取り込む" to ("Import from p5.js" to "从 p5.js 导入作品"),
    "端末内" to ("On device" to "设备内"),
    "作品の素材" to ("Work assets" to "作品素材"),
    "画像・音声・フォントなどを管理" to ("Manage images, audio, fonts and more" to "管理图片、音频、字体等素材"),
    "画像・音声・動画・フォント・データを追加できます" to ("Add images, audio, video, fonts and data" to "可添加图片、音频、视频、字体和数据"),
    "1ファイル50MBまで、1作品200MB・100ファイルまで" to ("Up to 50 MB per file; 200 MB and 100 files per work" to "每个文件最多 50 MB，每个作品最多 200 MB、100 个文件"),
    "素材を追加すると、ここに表示されます" to ("Added assets will appear here" to "添加的素材将显示在这里"),
    "パスをコピー" to ("Copy path" to "复制路径"),
    "素材を追加" to ("Add assets" to "添加素材"),
    "素材を削除" to ("Delete asset" to "删除素材"),
    "ファイル名" to ("File name" to "文件名"),
    "コード内のパスも新しい名前に変更してください" to ("Also update the path in your code" to "请同时更新代码中的路径"),
    "素材を保存できませんでした" to ("Could not save assets" to "无法保存素材"),
    "素材を追加できませんでした。ファイル名・サイズ・保存先を確認してください" to ("Could not add assets. Check names, sizes and save location." to "无法添加素材，请检查文件名、大小和保存位置"),
    "ファイルを処理中…" to ("Processing files…" to "正在处理文件…"),

    "編集時にプレビューを隠す" to ("Hide preview while editing" to "编辑时隐藏预览"),
    "縦画面でコード欄を選ぶと非表示になり、編集を終えると戻ります" to ("In portrait, hide the preview when the code field is focused; restore it when editing ends" to "竖屏时选择代码区域隐藏预览，结束编辑后恢复"),
    "プレビューを隠す設定が優先されます" to ("Hide preview takes priority" to "优先隐藏预览"),
    "縦画面の編集中だけプレビューを低く表示します" to ("Use a shallow preview while editing in portrait" to "竖屏编辑时缩小预览高度"),

    "アップデート" to ("Updates" to "更新"),
    "アップデートを確認" to ("Check for updates" to "检查更新"),
    "確認中…" to ("Checking…" to "正在检查…"),
    "新しいバージョンがあります" to ("A new version is available" to "有新版本可用"),
    "新しいアップデートはありません" to ("No new updates available" to "暂无新更新"),
    "公開済みのバージョンが見つかりません" to ("No published version found" to "未找到已发布的版本"),
    "バージョンを比較できませんでした" to ("Unable to compare versions" to "无法比较版本"),
    "確認できませんでした。通信環境を確認して、もう一度お試しください" to ("Couldn't check for updates. Check your connection and try again." to "无法检查更新。请检查网络连接后重试"),
    "配布ページを開く" to ("Open release page" to "打开发布页面"),
    "ブラウザーを開けませんでした" to ("Couldn't open a browser" to "无法打开浏览器"),
    "ライセンス情報" to ("License information" to "许可证信息"),
    "アプリのフォント" to ("App font" to "应用字体"),
    "標準フォント" to ("Default font" to "默认字体"),
    "TTF・OTF・TTCをインポート。設定画面とエディターに反映します" to ("Import TTF, OTF or TTC for the interface and editor" to "导入 TTF、OTF 或 TTC，应用于界面和编辑器"),
    "フォントをインポート" to ("Import font" to "导入字体"),
    "読み込み中" to ("Loading" to "正在加载"),
    "標準に戻す" to ("Use default" to "恢复默认"),
    "フォントの連字" to ("Ligatures" to "连字"),
    "対応フォントの連字を有効にします。コードの文字列は変わりません" to ("Enable ligatures in supported fonts. Code text is unchanged." to "启用字体支持的连字，不更改代码文本。"),
    "フォントを読み込めません。20MB以下のTTF・OTF・TTCを選んでください" to ("Could not load font. Choose a TTF, OTF or TTC up to 20 MB." to "无法加载字体。请选择不超过 20 MB 的 TTF、OTF 或 TTC。"),
    "反射するEDIT:RiNのテンプレート" to ("Bouncing EDIT:RiN template" to "EDIT:RiN 反弹模板"),
    "描画の縦横を切り替える" to ("Swap canvas width and height" to "切换画布横竖方向"),
    "録画を停止してから描画の向きを変更してください" to ("Stop recording before changing canvas orientation" to "请先停止录屏再更改画布方向"),
    "描画の向きを変更できませんでした" to ("Could not change canvas orientation" to "无法更改画布方向"),
    "%s作品" to ("%s works" to "%s 个作品"),
    "%s を入力" to ("Insert %s" to "输入 %s"),
    "プレビュー比率を変更: %s" to ("Change preview ratio: %s" to "更改预览比例：%s"),
    "%s件" to ("%s matches" to "%s 个匹配项"),
    "「%s」を削除しますか？" to ("Delete ‘%s’?" to "删除“%s”？"),
    "閉じる" to ("Close" to "关闭"),
    "作品・未保存" to ("Work · Unsaved" to "作品 · 未保存"),
    "作品" to ("Work" to "作品"),
    "作品を選択" to ("Select a work" to "选择作品"),
    "作品一覧を開く" to ("Open works" to "打开作品列表"),
    "追加" to ("Add" to "添加"),
    "作品名で検索" to ("Search by name" to "按名称搜索"),
    "検索をクリア" to ("Clear search" to "清除搜索"),
    "一致する作品がありません" to ("No matching works" to "没有匹配的作品"),
    "、選択中" to (", selected" to "，已选中"),
    "未保存の変更あり" to ("Unsaved changes" to "有未保存的更改"),
    "選択中" to ("Selected" to "已选中"),
    "タップして開く" to ("Tap to open" to "点击打开"),
    "編集・作品" to ("Edit & work" to "编辑与作品"),
    "元に戻す" to ("Undo" to "撤销"),
    "直前の編集を取り消す" to ("Undo the last edit" to "撤销上一次编辑"),
    "やり直す" to ("Redo" to "重做"),
    "取り消した編集をやり直す" to ("Redo the undone edit" to "重做已撤销的编辑"),
    "検索・置換" to ("Find & replace" to "查找与替换"),
    "文字列検索、置換、指定行へ移動" to ("Find, replace, or go to a line" to "查找、替换或跳转到指定行"),
    "コードを整形" to ("Format code" to "格式化代码"),
    "インデントと空行を整理" to ("Tidy indentation and blank lines" to "整理缩进和空行"),
    "プロジェクトファイル" to ("Project files" to "项目文件"),
    "実行環境" to ("Runtime" to "运行环境"),
    "p5.jsとp5.soundを作品ごとに設定" to ("Set p5.js and p5.sound for this work" to "为此作品设置 p5.js 和 p5.sound"),
    "p5.jsバージョン" to ("p5.js version" to "p5.js 版本"),
    "現在の標準" to ("Current" to "当前标准"),
    "旧作品向け" to ("Legacy" to "旧作品"),
    "音声再生・合成・解析を有効にします" to ("Enable audio playback, synthesis, and analysis" to "启用音频播放、合成和分析"),
    "実行環境を保存できませんでした" to ("Could not save runtime settings" to "无法保存运行环境设置"),
    "追加JavaScriptファイルを管理" to ("Manage supporting JavaScript files" to "管理附加 JavaScript 文件"),
    "変更履歴" to ("Revision history" to "修改历史"),
    "過去30回の保存状態を表示・復元" to ("View or restore the last 30 revisions" to "查看或恢复最近 30 次保存的版本"),
    "プレビュー比率" to ("Preview aspect ratio" to "预览比例"),
    "作品ごとにキャンバスの縦横比を設定" to ("Set the canvas aspect ratio for this work" to "设置此作品的画布比例"),
    "名前を変更" to ("Rename" to "重命名"),
    "作品タイトルを編集" to ("Edit the work name" to "编辑作品名称"),
    "複製" to ("Duplicate" to "复制作品"),
    "現在のコードからコピーを作成" to ("Create a copy of the current code" to "创建当前代码的副本"),
    "ファイル" to ("Files" to "文件"),
    "JSをインポート" to ("Import JS" to "导入 JS"),
    "外部のJavaScriptファイルを読み込む" to ("Open an external JavaScript file" to "读取外部 JavaScript 文件"),
    "JSを書き出す" to ("Export JS" to "导出 JS"),
    "現在の作品を.jsファイルとして保存" to ("Save the current work as a .js file" to "将当前作品保存为 .js 文件"),
    "削除" to ("Delete" to "删除"),
    "この作品を削除" to ("Delete this work" to "删除此作品"),
    "最後の1作品は削除できません" to ("The last work cannot be deleted" to "无法删除最后一个作品"),
    "画面を回転" to ("Rotate screen" to "旋转屏幕"),
    "設定" to ("Settings" to "设置"),
    "作品を追加" to ("Add a work" to "添加作品"),
    "作品メニュー" to ("Work menu" to "作品菜单"),
    "作品未選択" to ("No work selected" to "未选择作品"),
    " · 未保存" to (" · Unsaved" to " · 未保存"),
    "管理" to ("Manage" to "管理"),
    "スクリーンショットをPictures/EditKIROへ保存しました" to ("Screenshot saved to Pictures/EditKIRO" to "截图已保存到 Pictures/EditKIRO"),
    "スクリーンショットを保存できませんでした" to ("Could not save the screenshot" to "无法保存截图"),
    "録画をMovies/EditKIROへ保存しました" to ("Recording saved to Movies/EditKIRO" to "录屏已保存到 Movies/EditKIRO"),
    "録画を保存できませんでした" to ("Could not save the recording" to "无法保存录屏"),
    "プレビューをスクリーンショット" to ("Capture preview" to "截取预览"),
    "録画を停止" to ("Stop recording" to "停止录屏"),
    "プレビューを録画" to ("Record preview" to "录制预览"),
    "プレビューを全画面表示" to ("Full-screen preview" to "全屏预览"),
    "全画面表示を閉じる" to ("Exit full screen" to "退出全屏"),
    "録画を停止してから全画面表示を閉じてください" to ("Stop recording before exiting full screen" to "请先停止录屏再退出全屏"),
    "プレビュー操作を閉じる" to ("Close preview controls" to "关闭预览控件"),
    "プレビュー操作を開く" to ("Open preview controls" to "打开预览控件"),
    "再生" to ("Play" to "播放"),
    "一時停止" to ("Pause" to "暂停"),
    "再読み込み" to ("Reload" to "重新加载"),
    "ログ" to ("Console" to "日志"),
    "保存済み状態に戻す" to ("Revert to saved" to "恢复到已保存状态"),
    "作品を保存" to ("Save work" to "保存作品"),
    "ログはありません" to ("No messages" to "暂无日志"),
    "編集キー" to ("Editing keys" to "编辑按键"),
    "検索と置換" to ("Find and replace" to "查找与替换"),
    "インデント" to ("Indent" to "增加缩进"),
    "インデントを戻す" to ("Outdent" to "减少缩进"),
    "左へ移動" to ("Move left" to "向左移动"),
    "上へ移動" to ("Move up" to "向上移动"),
    "下へ移動" to ("Move down" to "向下移动"),
    "右へ移動" to ("Move right" to "向右移动"),
    "コメントを入力" to ("Insert comment" to "插入注释"),
    "プレビューとエディターの分割を調整" to ("Adjust preview/editor split" to "调整预览与编辑器分隔"),
    "プレビューを広げる" to ("Expand preview" to "扩大预览"),
    "エディターを広げる" to ("Expand editor" to "扩大编辑器"),
    "空のコード" to ("Empty code" to "空代码"),
    "正方形" to ("Square" to "正方形"),
    "標準・横" to ("Standard landscape" to "标准横向"),
    "ワイド" to ("Wide" to "宽屏"),
    "縦長" to ("Portrait" to "纵向"),
    "編集" to ("Edit" to "编辑"),
    "ファイルを追加" to ("Add file" to "添加文件"),
    "JSファイルを追加" to ("Add JS file" to "添加 JS 文件"),
    "JSファイルを編集" to ("Edit JS file" to "编辑 JS 文件"),
    "ファイル名（.js）" to ("File name (.js)" to "文件名（.js）"),
    "JavaScriptコード" to ("JavaScript code" to "JavaScript 代码"),
    "追加ファイルは名前順にsketch.jsより先に実行されます。" to ("Supporting files run in name order before sketch.js." to "附加文件按名称顺序在 sketch.js 之前执行。"),
    "保存" to ("Save" to "保存"),
    "キャンセル" to ("Cancel" to "取消"),
    "検索する文字列" to ("Find text" to "查找内容"),
    "大文字・小文字を区別" to ("Match case" to "区分大小写"),
    "0件" to ("0 matches" to "0 个匹配项"),
    "前へ" to ("Previous" to "上一个"),
    "次へ" to ("Next" to "下一个"),
    "置換後の文字列" to ("Replace with" to "替换为"),
    "置換" to ("Replace" to "替换"),
    "すべて置換" to ("Replace all" to "全部替换"),
    "行番号" to ("Line numbers" to "行号"),
    "移動" to ("Go" to "跳转"),
    "作品フォルダーを選択" to ("Choose work folder" to "选择作品文件夹"),
    "作品は選択したフォルダーに保存されます。再インストール後も同じフォルダーを選択すれば復元できます。" to ("Works are saved in this folder. Select it again after reinstalling to restore them." to "作品保存在所选文件夹中。重新安装后选择同一文件夹即可恢复。"),
    "フォルダーを選択" to ("Choose folder" to "选择文件夹"),
    "新しい作品" to ("New work" to "新作品"),
    "名前と描画比率を選んでスタート" to ("Choose a name and aspect ratio" to "选择名称和画布比例"),
    "作品名" to ("Work name" to "作品名称"),
    "描画比率" to ("Canvas aspect ratio" to "画布比例"),
    "端末" to ("Device" to "设备"),
    "端末の画面比率" to ("Device screen ratio" to "设备屏幕比例"),
    "端末の向きに合わせて比率が切り替わります" to ("The ratio follows the device orientation" to "比例会随设备方向切换"),
    "作品の表示枠を選択" to ("Choose the work frame" to "选择作品显示框"),
    "キャンバスの動作" to ("Canvas behavior" to "画布行为"),
    "固定サイズ" to ("Fixed size" to "固定尺寸"),
    "画面に合わせる" to ("Fit to screen" to "适应屏幕"),
    "指定した描画サイズを維持し、表示だけを枠に合わせます" to ("Keep the specified canvas size and fit only its display" to "保持指定的画布尺寸，仅调整显示以适应预览框"),
    "作業領域に合わせてresizeCanvas()を実行します" to ("Run resizeCanvas() when the workspace changes" to "工作区域变化时执行 resizeCanvas()"),
    "シンプルな円のテンプレート" to ("Simple circle template" to "简单圆形模板"),
    "選択した比率を作品に保存します。現在の作品のコードはコピーしません。" to ("The ratio is saved with the work. Existing code is not copied." to "所选比例将保存到作品中，不会复制当前代码。"),
    "作成" to ("Create" to "创建"),
    "作品名を変更" to ("Rename work" to "重命名作品"),
    "変更" to ("Apply" to "应用"),
    "作品を削除" to ("Delete work" to "删除作品"),
    "戻る" to ("Back" to "返回"),
    "外観" to ("Appearance" to "外观"),
    "エディター" to ("Editor" to "编辑器"),
    "保存とバックアップ" to ("Storage" to "存储"),
    "テーマとシステムUI" to ("Theme and system UI" to "主题与系统界面"),
    "テーマ" to ("Theme" to "主题"),
    "端末の設定とMaterial Youに合わせます" to ("Follow device settings and Material You" to "跟随设备设置与 Material You"),
    "黒を基調とした表示" to ("Black-based appearance" to "黑色主题"),
    "白を基調とした表示" to ("White-based appearance" to "白色主题"),
    "自動" to ("System" to "跟随系统"),
    "ダーク" to ("Dark" to "深色"),
    "ライト" to ("Light" to "浅色"),
    "ステータスバー" to ("Status bar" to "状态栏"),
    "横画面では自動的に非表示になります" to ("Automatically hidden in landscape" to "横屏时自动隐藏"),
    "時刻や通知アイコンを表示します" to ("Show time and notification icons" to "显示时间和通知图标"),
    "横画面でノッチ部分まで使用" to ("Use cutout area in landscape" to "横屏时使用刘海区域"),
    "余白なしで表示します。ノッチの位置は内容が隠れる場合があります" to ("Use the full width. The cutout may obscure content." to "使用全部宽度。刘海可能遮挡内容。"),
    "ノッチを避ける余白を確保します" to ("Keep content clear of the cutout" to "保留避开刘海的边距"),
    "画面の向きを固定" to ("Disable automatic rotation" to "关闭自动旋转"),
    "自動回転を停止し、上部の↻ボタンで縦横を切り替えます" to ("Use the top rotate button instead of automatic rotation" to "使用顶部旋转按钮切换方向"),
    "端末の向きに合わせて画面を回転します" to ("Rotate with the device" to "跟随设备方向旋转"),
    "編集とプレビューの動作" to ("Editing and preview behavior" to "编辑与预览行为"),
    "作品切替時に自動実行" to ("Run when switching works" to "切换作品时自动运行"),
    "作品を選択するとプレビューを更新します" to ("Update the preview when a work is selected" to "选择作品时更新预览"),
    "編集時にプレビューを縮小" to ("Compact preview while editing" to "编辑时缩小预览"),
    "縦画面の編集中は横幅いっぱいの浅いプレビューに切り替えます。作品の保存比率は変更しません" to ("Use a shallow full-width preview while editing in portrait, without changing the saved ratio." to "竖屏编辑时使用全宽的低矮预览，不更改已保存比例。"),
    "サイズ調整バー" to ("Resize divider" to "尺寸调整分隔线"),
    "プレビューとエディターの間にドラッグ操作を表示します" to ("Show a draggable divider between preview and editor" to "显示预览与编辑器之间的可拖动分隔线"),
    "境界線とドラッグ操作を非表示にします" to ("Hide the divider and disable dragging" to "隐藏分隔线并禁用拖动"),
    "横画面のプレビュー幅" to ("Landscape preview width" to "横屏预览宽度"),
    "プレビューに使う横幅を調整します" to ("Adjust the space allocated to preview and editor" to "调整预览与编辑器占用的空间"),
    "全画面でも描画サイズを維持" to ("Preserve work size in full screen" to "全屏时保持作品尺寸"),
    "通常プレビューと同じ座標・縦横比で実行し、表示だけを拡大します" to ("Keep preview coordinates and ratio; scale only the display" to "保持预览坐标和比例，仅放大显示"),
    "自動インデント" to ("Auto indent" to "自动缩进"),
    "改行時に現在の字下げを引き継ぎ、括弧内を一段下げます" to ("Carry indentation to new lines and indent inside braces" to "换行时保留缩进，并在括号内增加一级"),
    "コードの各行に番号を表示します" to ("Show a number for each code line" to "为每行代码显示行号"),
    "編集キー" to ("Keyboard toolbar" to "键盘工具栏"),
    "編集中にTAB、カーソル移動、記号ボタンを表示します" to ("Show TAB, cursor and symbol buttons while editing" to "编辑时显示 TAB、光标和符号按钮"),
    "入力候補" to ("p5.js suggestions" to "p5.js 输入建议"),
    "p5.jsの関数名や変数名の候補を表示します" to ("Suggest p5.js function and built-in variable names" to "显示 p5.js 函数名和内置变量名"),
    "移動キーを表示" to ("Show navigation keys" to "显示导航键"),
    "操作パネルにTABとカーソルキーを表示します" to ("Show TAB and arrow keys in the toolbar" to "在工具栏中显示 TAB 和方向键"),
    "記号キーを表示" to ("Show symbol keys" to "显示符号键"),
    "操作パネルに括弧や記号キーを表示します" to ("Show brackets and symbols in the toolbar" to "在工具栏中显示括号和符号键"),
    "編集キーを小さくする" to ("Compact keys" to "紧凑按键"),
    "操作パネルの高さとキー幅を小さくします" to ("Reduce toolbar height and key width" to "减小工具栏高度和按键宽度"),
    "未保存のコードを復元" to ("Recover unsaved edits" to "恢复未保存的编辑"),
    "未保存の変更を一時保存し、次回起動時に復元します" to ("Keep a draft and restore it on next launch" to "暂存未保存的更改并在下次启动时恢复"),
    "文字サイズ" to ("Font size" to "字号"),
    "コードエディターの文字サイズ" to ("Code editor font size" to "代码编辑器字号"),
    "保存先とファイル入出力" to ("Save location and file transfer" to "保存位置与文件导入导出"),
    "作品フォルダー" to ("Work folder" to "作品文件夹"),
    "保存先を変更" to ("Change folder" to "更改文件夹"),
    "JavaScriptファイル" to ("JavaScript files" to "JavaScript 文件"),
    ".js を作品として読み込む、または現在のコードを書き出します" to ("Import a .js file as a work or export the current code" to "将 .js 文件导入为作品，或导出当前代码"),
    "作品と設定のバックアップ" to ("Full backup" to "完整备份"),
    "すべての作品とエディター設定をZIPで保存・復元します" to ("Save or restore all works and editor settings as ZIP" to "以 ZIP 保存或恢复所有作品和编辑器设置"),
    "復元" to ("Restore" to "恢复"),
    "ZIP保存" to ("Save ZIP" to "保存 ZIP"),
    "未選択" to ("Not selected" to "未选择"),
    "選択済みフォルダー" to ("Selected folder" to "已选文件夹"),
    "言語" to ("Language" to "语言"),
    "アプリの表示言語" to ("App display language" to "应用显示语言"),
    "システムデフォルト" to ("System default" to "跟随系统"),
    "対応していない端末言語の場合は英語を使用します" to ("Unsupported device languages use English" to "不支持的设备语言将使用英语"),
    "保存先を作成できませんでした" to ("Could not create the destination" to "无法创建保存位置"),
    "保存先を開けませんでした" to ("Could not open the destination" to "无法打开保存位置"),
    "保存先を利用できません" to ("Destination unavailable" to "保存位置不可用"),
    "保存できませんでした。保存先を確認して再試行してください" to ("Could not save. Check the folder and retry." to "无法保存。请检查文件夹后重试。"),
    "比率を保存できませんでした。保存先を確認してください" to ("Could not save the ratio. Check the folder." to "无法保存比例。请检查文件夹。"),
    "録画を停止してから再実行してください" to ("Stop recording before running again" to "请先停止录屏再重新运行"),
    "保存できませんでした。保存先フォルダーを確認してください" to ("Could not save. Check the destination folder." to "无法保存。请检查目标文件夹。"),
    "作品ファイルを読み込めません。元のファイルは上書きしていません" to ("Could not read works. The original file was not overwritten." to "无法读取作品。原文件未被覆盖。"),
    "JSファイルを読み込めませんでした" to ("Could not import JS" to "无法导入 JS"),
    "JSファイルを書き出せませんでした" to ("Could not export JS" to "无法导出 JS"),
    "バックアップを書き出せませんでした" to ("Could not export backup" to "无法导出备份"),
    "バックアップを復元できませんでした" to ("Could not restore backup" to "无法恢复备份"),
    "作品を保存できませんでした。保存先を確認してください" to ("Could not save the work. Check the folder." to "无法保存作品。请检查文件夹。"),
    "保存先フォルダーにアクセスできません" to ("Cannot access the folder" to "无法访问文件夹"),
    "保存先フォルダーを読み込めません" to ("Cannot read the folder" to "无法读取文件夹"),
    "作品ファイルを読み込めません" to ("Cannot read the work file" to "无法读取作品文件"),
    "作品ファイルの形式を読み取れません" to ("Invalid work file format" to "作品文件格式无效"),
    "作品ファイルが空です" to ("Work file is empty" to "作品文件为空")
)
