package com.hikariatelier.app

internal fun resolveUiLanguage(selection: String, deviceLanguage: String): String {
    val language = if (selection == "system") deviceLanguage.lowercase().substringBefore('-').substringBefore('_') else selection
    return if (language in setOf("ja", "en", "zh")) language else "en"
}

internal fun translateUi(source: String, language: String): String {
    if (language == "ja") return source
    val entry = uiTranslations[source] ?: return source
    return if (language == "zh") entry.second else entry.first
}

internal val uiTranslations = mapOf(
    "自分の作品" to ("My works" to "我的作品"),
    "サンプル・閲覧専用" to ("Samples · Read only" to "示例 · 只读"),
    "コピーして編集" to ("Copy to edit" to "复制后编辑"),
    "未分類" to ("Unfiled" to "未分类"),
    "フォルダー管理" to ("Manage folders" to "管理文件夹"),
    "フォルダーへ移動" to ("Move to folder" to "移至文件夹"),
    "保存先フォルダー" to ("Destination folder" to "目标文件夹"),
    "新規フォルダー" to ("New folder" to "新建文件夹"),
    "フォルダー名" to ("Folder name" to "文件夹名称"),
    "フォルダーの順序を保存しました" to ("Folder order saved" to "已保存文件夹顺序"),
    "長押しで左右に入れ替え" to ("Long-press and drag to reorder" to "长按并左右拖动排序"),
    "更新" to ("Update" to "更新"),
    "タグを削除" to ("Delete tag" to "删除标签"),
    "サンプルをコピーできませんでした" to ("Could not copy the sample" to "无法复制示例"),
    "自分の作品にコピーしました" to ("Copied to My works" to "已复制到我的作品"),
    "フォルダーを作成できませんでした" to ("Could not create the folder" to "无法创建文件夹"),
    "フォルダーを変更できませんでした" to ("Could not rename the folder" to "无法重命名文件夹"),
    "フォルダーを削除できませんでした" to ("Could not delete the folder" to "无法删除文件夹"),
    "作品を移動できませんでした" to ("Could not move the works" to "无法移动作品"),
    "作品を移動しました" to ("Works moved" to "已移动作品"),
    "サンプル原本は変更せず、自分の作品にコピーします。" to ("Copy to My works to edit. The original sample is kept." to "复制到我的作品后编辑，保留原始示例。"),
    "フォルダーを削除しても作品は未分類に残ります。" to ("Deleting a folder keeps its works in Unfiled." to "删除文件夹后，作品保留在未分类中。"),
    "サンプルフォルダーを開く" to ("Open sample folder" to "打开示例文件夹"),
    "破棄" to ("Discard" to "丢弃"),
    "録画を破棄できませんでした" to ("Could not discard the recording" to "无法丢弃录制"),
    "一緒に更新する参照を選択してください。未選択のコードは変更しません。" to ("Select references to update together. Unselected code is kept." to "请选择一并更新的引用，未选择的代码保持不变。"),
    "完全一致する文字列のパスだけを表示します。動的なパスやテンプレート文字列は対象外です。" to ("Only exact literal paths are shown. Dynamic paths and template strings are excluded." to "仅显示完全匹配的字符串路径，不包括动态路径和模板字符串。"),
    "更新できる参照候補はありません" to ("No references available to update" to "没有可更新的引用"),
    "名前・メモを編集" to ("Edit name and note" to "编辑名称和备注"),
    "スナップショットを記録" to ("Record snapshot" to "记录快照"),
    "名前（任意）" to ("Name (optional)" to "名称（可选）"),
    "メモ（任意）" to ("Note (optional)" to "备注（可选）"),
    "スナップショットの名前・メモを保存できませんでした。" to ("Could not save the snapshot name and note." to "无法保存快照名称和备注。"),
    "スナップショットの名前・メモを保存しました" to ("Snapshot name and note saved" to "已保存快照名称和备注"),
    "変更未反映" to ("Not applied" to "更改未应用"),
    "変更を実行" to ("Run changes" to "运行更改"),
    "エラーは前回の実行結果です" to ("These errors are from the previous run" to "这些错误来自上一次运行"),
    "素材名と参照パスを保存できませんでした。編集内容は保持しています" to ("Could not save the asset name and references. Your edits are kept." to "无法保存素材名称和引用路径，编辑内容已保留。"),
    "素材名と選択した参照パスを更新しました" to ("Asset name and selected references updated" to "已更新素材名称和所选引用路径"),
    "録画の準備中です" to ("Preparing recording" to "正在准备录制"),
    "保存待ちの録画を保存または破棄してください" to ("Save or discard the pending recording first" to "请先保存或丢弃待保存的录制"),
    "保存待ちの録画を破棄しますか？" to ("Discard the pending recording?" to "丢弃待保存的录制吗？"),
    "この録画はまだ保存されていません。破棄すると復元できません。" to ("This recording has not been saved. Discarding it cannot be undone." to "此录制尚未保存，丢弃后无法恢复。"),
    "録画は保持されています。再保存するか、別の保存先を選んでください。" to ("Your recording is kept. Retry saving or choose another destination." to "录制已保留，请重新保存或选择其他保存位置。"),
    "再保存" to ("Retry saving" to "重新保存"),
    "別の保存先を選ぶ" to ("Choose another destination" to "选择其他保存位置"),
    "録画を破棄" to ("Discard recording" to "丢弃录制"),
    "画像を開けませんでした" to ("Could not open the image" to "无法打开图片"),
    "選択" to ("Select" to "选择"),
    "名前変更" to ("Rename" to "重命名"),
    "すべて選択 / 解除" to ("Select / deselect all" to "全选 / 取消全选"),
    "編集中の作品へ移動" to ("Jump to the work being edited" to "跳转到正在编辑的作品"),
    "選択した作品にタグ付け" to ("Tag selected works" to "为所选作品添加标签"),
    "選択した作品からタグを外す" to ("Remove tag from selected works" to "从所选作品移除标签"),
    "選択した作品を書き出す" to ("Export selected works" to "导出所选作品"),
    "選択した作品を削除" to ("Delete selected works" to "删除所选作品"),
    "選択を終了" to ("Exit selection" to "结束选择"),
    "作品を削除しました" to ("Works deleted" to "已删除作品"),
    "作品を複製しました" to ("Work duplicated" to "已复制作品"),
    "作品を複製できませんでした" to ("Could not duplicate the work" to "无法复制作品"),
    "作品を削除できませんでした" to ("Could not delete works" to "无法删除作品"),
    "作品を復元しました" to ("Works restored" to "已恢复作品"),
    "作品を復元できませんでした" to ("Could not restore works" to "无法恢复作品"),
    "次の作品を削除します。削除後に「元に戻す」で取り消せます。" to ("Delete the following works? You can use Undo immediately after deletion." to "要删除以下作品吗？删除后可立即使用“撤销”恢复。"),
    "ファイルを保存しました" to ("File saved" to "文件已保存"),
    "ファイルを保存できませんでした" to ("Could not save the file" to "无法保存文件"),
    "ファイルを選択できませんでした" to ("Could not select a file" to "无法选择文件"),
    "URLファイルを取得できません" to ("Could not fetch the URL file" to "无法获取 URL 文件"),
    "ファイルデータを読み出せませんでした" to ("Could not read the file data" to "无法读取文件数据"),
    "保存要求が多すぎます。保存が完了するまでお待ちください" to ("Too many save requests. Wait for saving to finish." to "保存请求过多，请等待保存完成。"),
    "ファイルは256MiB以下で保存してください" to ("Files must be 256 MiB or smaller" to "文件大小不能超过 256 MiB"),
    "ファイルの保存を開始できませんでした" to ("Could not start saving the file" to "无法开始保存文件"),
    "ファイル名・相対パス" to ("File name or relative path" to "文件名或相对路径"),
    "ファイル設定" to ("File options" to "文件选项"),
    "同じ名前のファイルが存在します" to ("A file with this name already exists" to "已存在同名文件"),
    "HTML・マークアップ" to ("HTML / markup" to "HTML / 标记"),
    "CSSコード" to ("CSS code" to "CSS 代码"),
    "JSONデータ" to ("JSON data" to "JSON 数据"),
    "テキスト" to ("Text" to "文本"),
    "index.html、style.css、.mjs、.json などのテキストと、scripts/main.js のような相対パスを使用できます。読み込み方法は実行環境で設定します。" to
        ("Add text files such as index.html, style.css, .mjs and .json, including relative paths like scripts/main.js. Choose how they load in Runtime settings." to "可以添加 index.html、style.css、.mjs、.json 等文本文件，也可以使用 scripts/main.js 等相对路径。请在运行环境中设置加载方式。"),
    "プロジェクトの読み込み設定" to ("Project loading settings" to "项目加载设置"),
    "内蔵ライブラリの読み込み順" to ("Bundled library loading order" to "内置库加载顺序"),
    "HTML作品では、p5.jsとライブラリをHTML内のscriptタグで指定します。" to
        ("For HTML works, specify p5.js and libraries with script tags in the HTML." to "HTML 作品中的 p5.js 和库请使用 HTML 内的 script 标签指定。"),
    "通常JavaScript" to ("Classic JavaScript" to "普通 JavaScript"),
    "モジュール" to ("Module" to "模块"),
    "HTMLページ" to ("HTML page" to "HTML 页面"),
    "開始するHTMLファイル" to ("HTML entry file" to "HTML 入口文件"),
    "開始するモジュール" to ("Module entry file" to "模块入口文件"),
    "ファイルを追加してください" to ("Add a file first" to "请先添加文件"),
    "index.html を優先します。メインの import/export、またはメインと通常JSが空で .mjs が1つの場合はモジュールを実行します。" to
        ("Prefers index.html. Runs a module for main import/export, or one .mjs file when the main and classic JS are empty." to "优先使用 index.html。主文件有 import/export，或主文件和普通 JS 为空且只有一个 .mjs 文件时，运行模块。"),
    "HTML内の script タグでライブラリ・読み込み順・モジュールを指定してください。" to
        ("Set libraries, script order and modules using script tags in the HTML." to "请使用 HTML 中的 script 标签指定库、加载顺序和模块。"),
    "JavaScriptの読み込み順" to ("JavaScript loading order" to "JavaScript 加载顺序"),
    "名前順に戻す" to ("Reset to name order" to "恢复为名称顺序"),
    "上へ" to ("Move up" to "上移"),
    "下へ" to ("Move down" to "下移"),
    "外部ライブラリ（HTTPS）" to ("External libraries (HTTPS)" to "外部库（HTTPS）"),
    "通常JSは登録順に作品コードより先に実行します。モジュールはブラウザーのモジュール読み込みに従います。" to
        ("Classic scripts run in the listed order before the sketch code. Modules follow the browser's module loading behavior." to "普通脚本按列表顺序在作品代码之前运行，模块遵循浏览器的模块加载行为。"),
    "ライブラリのHTTPS URL" to ("Library HTTPS URL" to "库的 HTTPS URL"),
    "モジュールとして読み込む" to ("Load as a module" to "作为模块加载"),
    "p5.jsのHTTPS URL（任意）" to ("p5.js HTTPS URL (optional)" to "p5.js HTTPS URL（可选）"),
    "空欄の場合は内蔵p5.jsを使用します。外部URLはインターネット接続が必要です。" to
        ("Leave blank to use bundled p5.js. External URLs need an internet connection." to "留空时使用内置 p5.js，外部 URL 需要网络连接。"),
    "設定は edit-rin.json に保存され、作品と一緒に持ち運べます。" to
        ("Settings are saved in edit-rin.json and travel with the work." to "设置保存在 edit-rin.json 中，可随作品一起传输。"),
    "edit-rin.json の設定を読み取れません。プロジェクトファイルから修正してください。" to
        ("Could not read edit-rin.json. Fix it in Project files." to "无法读取 edit-rin.json，请在项目文件中修正。"),
    "開始するファイルまたはHTTPS URLを確認してください。" to ("Check the entry file or HTTPS URL." to "请检查入口文件或 HTTPS URL。"),
    "水彩・鉛筆の表現（p5.js 2.3.4 / WEBGL）" to ("Watercolor and pencils (p5.js 2.3.4 / WEBGL)" to "水彩和铅笔效果（p5.js 2.3.4 / WEBGL）"),
    "作品を読み込めませんでした。編集内容は保持しています" to ("Could not load work. Your edits are kept." to "无法读取作品，编辑内容已保留。"),
    "すべてのログを表示" to ("Show all logs" to "显示所有日志"),
    "エラーだけ表示" to ("Show errors only" to "仅显示错误"),
    "エラーはありません" to ("No errors" to "没有错误"),
    "最新へ" to ("Latest" to "最新"),
    "コード内の参照候補" to ("Possible code references" to "代码中的引用候选"),
    "文字列が一致する箇所を表示します。動的なパスは検出できません。" to ("Shows matching text. Dynamic paths cannot be detected." to "显示匹配的文本，无法检测动态路径。"),
    "一致する参照候補はありません" to ("No matching references" to "没有匹配的引用"),
    "先頭50件を表示" to ("Showing the first 50 matches" to "显示前50个匹配项"),
    "削除してもコードは変更されません。" to ("Deleting an asset does not update the code." to "删除素材不会修改代码。"),
    "テンプレート管理" to ("Manage templates" to "管理模板"),
    "テンプレート名で検索" to ("Search template names" to "按模板名称搜索"),
    "一致するテンプレートはありません" to ("No matching templates" to "没有匹配的模板"),
    "現在の作品から更新" to ("Update from current work" to "从当前作品更新"),
    "テンプレート名を変更" to ("Rename template" to "重命名模板"),
    "テンプレートを更新" to ("Update template" to "更新模板"),
    "現在の作品の編集内容・素材・実行設定で上書きします。作成済みの作品には影響しません。" to ("Replace this template with the current edits, assets and runtime settings. Existing works are kept." to "使用当前编辑内容、素材和运行设置覆盖模板，已创建的作品将保留。"),
    "削除しても作成済みの作品には影響しません。" to ("Existing works are kept when a template is deleted." to "删除模板不会影响已创建的作品。"),
    "素材" to ("Assets" to "素材"),
    "プレビューを準備できませんでした" to ("Could not prepare preview" to "无法准备预览"),
    "保存競合" to ("Save conflict" to "保存冲突"),
    "保存失敗" to ("Save failed" to "保存失败"),
    "処理中" to ("Working" to "处理中"),
    "保存済み" to ("Saved" to "已保存"),
    "保存済みの内容に戻す" to ("Restore saved content" to "恢复已保存的内容"),
    "この作品のコード・補助ファイル・設定の未保存変更とUndo履歴を破棄します。復元しますか？" to ("Discard unsaved changes to this work’s code, supporting files and settings, and its Undo history?" to "将丢弃当前作品的代码、辅助文件、设置的未保存更改以及撤销历史。是否恢复？"),
    "外部変更と統合" to ("Merge external changes" to "合并外部更改"),
    "未編集の作品には外部変更を反映します。同じ作品に両方の変更がある場合は、現在の編集を別作品として保存して両方を保持します。" to ("Apply external changes to unedited works. When both versions changed the same work, save the current edits as a separate work to keep both." to "将外部更改应用于未编辑的作品。如果同一作品的两个版本均有更改，将当前编辑另存为新作品以保留两者。"),
    "統合" to ("Merge" to "合并"),
    "作品を読み込めませんでした" to ("Could not load works" to "无法读取作品"),
    "保存先にアクセスできないか、保存データを読み込めません。元のデータは保持しています。保存先を再接続して再試行してください。" to ("The saved data or its folder could not be read. Original data is kept. Reconnect the folder and try again." to "无法访问保存位置或读取保存的数据，原始数据已保留。请重新连接保存位置后重试。"),
    "保存先を再接続" to ("Reconnect save folder" to "重新连接保存位置"),
    "復元先を確認できない下書き" to ("Draft needs recovery review" to "需要确认恢复位置的草稿"),
    "保存先または保存済み内容が異なるため、自動復元を止めました。下書きを別作品として復元できます。" to ("The folder or saved content has changed, so automatic recovery stopped. Recover this draft as a separate work." to "保存位置或已保存的内容不同，已停止自动恢复。可以将草稿恢复为新作品。"),
    "別作品として復元" to ("Recover as a new work" to "恢复为新作品"),
    "下書きを破棄" to ("Discard draft" to "丢弃草稿"),
    "前の保存データから復旧しました" to ("Recovered the previous saved version" to "已从之前保存的数据恢复"),
    "保存先に別の変更があります。外部変更と統合してください" to ("The save folder contains other changes. Merge external changes to continue." to "保存位置中存在其他更改，请合并外部更改。"),
    "作品を読み込めませんでした。保存先を再接続してください" to ("Could not load works. Reconnect the save folder." to "无法读取作品，请重新连接保存位置。"),
    "変更を統合できませんでした。編集内容は保持しています" to ("Could not merge changes. Your edits are kept." to "无法合并更改，编辑内容已保留。"),
    "外部変更と統合しました。競合した編集は別作品として保持しました" to ("Merged external changes. Conflicting edits were kept as separate works." to "已合并外部更改，冲突的编辑已另存为新作品。"),
    "外部変更と統合しました" to ("Merged external changes" to "已合并外部更改"),
    "下書きを復元できませんでした" to ("Could not recover draft" to "无法恢复草稿"),
    "下書きを別作品として復元しました" to ("Recovered drafts as separate works" to "已将草稿恢复为新作品"),
    "自作テンプレートを検索・名前変更・更新" to ("Search, rename and update your templates" to "搜索、重命名和更新自定义模板"),
    "作品の全ファイルを保存" to ("Save all files in this work" to "保存作品中的所有文件"),
    "自作テンプレート" to ("My templates" to "自定义模板"),
    "標準テンプレート" to ("Built-in templates" to "内置模板"),
    "テンプレートとして保存" to ("Save as template" to "保存为模板"),
    "テンプレート名" to ("Template name" to "模板名称"),
    "コード・素材・実行設定を新規作品のひな形にする" to ("Reuse code, assets and runtime settings in new works" to "将代码、素材和运行设置用作新作品的模板"),
    "作品メニューの「テンプレートとして保存」から登録できます。" to ("Register a template with Save as template in the work menu." to "可从作品菜单的“保存为模板”进行注册。"),
    "コード・補助ファイル・素材・実行設定をそのまま引き継ぎます。" to ("Keep the template's code, supporting files, assets and runtime settings." to "保留模板的代码、辅助文件、素材和运行设置。"),
    "現在の編集内容・補助ファイル・素材・実行設定を保存します。" to ("Save current edits, supporting files, assets and runtime settings." to "保存当前编辑内容、辅助文件、素材和运行设置。"),
    "テンプレートを保存しました" to ("Template saved" to "模板已保存"),
    "テンプレートを保存できませんでした" to ("Could not save template" to "无法保存模板"),
    "テンプレートを削除" to ("Delete template" to "删除模板"),
    "テンプレートを削除しました" to ("Template deleted" to "模板已删除"),
    "テンプレートを削除できませんでした" to ("Could not delete template" to "无法删除模板"),
    "「%s」を削除します。作成済みの作品には影響しません。" to ("Delete \"%s\"? Existing works will be kept." to "删除“%s”？已创建的作品将保留。"),
    "テンプレートを読み込めませんでした。保存データは変更していません。" to ("Could not load templates. Saved data has been kept." to "无法读取模板。保存的数据未被更改。"),
    "プレビューの準備ができてから再度お試しください" to ("Try again when the preview is ready" to "请在预览准备就绪后重试"),
    "JavaScriptファイルを選択してください" to ("Select a JavaScript file" to "请选择 JavaScript 文件"),
    "シェーダー" to ("Shader" to "着色器"),
    "画像を保存するにはストレージへのアクセスを許可してください" to ("Allow storage access to save images" to "请允许访问存储空间以保存图像"),
    "テンプレート種別" to ("Template type" to "模板类型"),
    "2D基本" to ("Basic 2D" to "基础 2D"),
    "3D WebGL" to ("3D WebGL" to "3D WebGL"),
    "物理演算" to ("Physics" to "物理模拟"),
    "WebGPU" to ("WebGPU" to "WebGPU"),
    "＋ パラメータ追加" to ("＋ Add parameter" to "＋ 添加参数"),
    "パラメータ追加" to ("Add parameter" to "添加参数"),
    "コードに直接挿入" to ("Insert into code" to "直接插入代码"),
    "数値" to ("Number" to "数值"),
    "色" to ("Color" to "颜色"),
    "真偽値" to ("Boolean" to "布尔值"),
    "変数名（英字で開始）" to ("Name (start with a letter)" to "名称（以英文字母开头）"),
    "表示ラベル" to ("Display label" to "显示标签"),
    "最小値" to ("Minimum" to "最小值"),
    "最大値" to ("Maximum" to "最大值"),
    "ステップ" to ("Step" to "步长"),
    "名前は英数字と_、ラベルは40文字以内。名前の重複は不可。数値は最小値 < 最大値、初期値は範囲内、ステップは正数。最大16個。" to ("Use letters, digits and _ for names; labels up to 40 characters. Names must be unique. Minimum < maximum, default within range, positive step. Up to 16 parameters." to "名称使用英文字母、数字和_，标签最多40个字符。名称不可重复。最小值 < 最大值，默认值须在范围内，步长须为正数。最多16个参数。"),
    "変数名は半角英数字と_（英字開始）、ラベルは40文字以内。作品ごとに最大16個まで追加できます。" to ("Variable names use alphanumeric characters and _ (start with letter). Labels up to 40 characters; up to 16 parameters per sketch." to "变量名支持半角英文字母、数字和_（以英文字母开头），标签上限40字符。每个作品最多可设置16个参数。"),
    "パラメータを追加できませんでした" to ("Could not add parameter" to "无法添加参数"),
    "パラメータを追加できませんでした。入力値を確認してください" to ("Could not add parameter. Please check input values." to "无法添加参数，请检查输入内容。"),
    "スニペット" to ("Snippets" to "代码片段"),
    "挿入先の関数を確認して選択してください。選択中のコードは置き換えます。" to ("Check the insertion function before choosing. Selected code will be replaced." to "选择前请确认插入位置的函数。所选代码将被替换。"),
    "挿入したいスニペットを選択してください。カーソル位置（または選択範囲）に挿入されます。" to ("Select a snippet to insert at the current cursor position or replace the selected code." to "选择要插入的代码片段，代码将插入到当前光标所在位置或替换选中内容。"),
    "アニメーション・数学" to ("Animation & math" to "动画与数学"),
    "sin/cos周期運動" to ("sin/cos oscillation" to "sin/cos 周期运动"),
    "lerp補間" to ("lerp interpolation" to "lerp 插值"),
    "map値マッピング" to ("map value mapping" to "map 数值映射"),
    "draw() 内に挿入" to ("Insert inside draw()" to "插入到 draw() 内"),
    "setup() 内に挿入" to ("Insert inside setup()" to "插入到 setup() 内"),
    "関数の外に挿入" to ("Insert outside functions" to "插入到函数外"),
    "draw() 内に挿入（Particleが必要）" to ("Inside draw() (requires Particle)" to "插入到 draw() 内（需要 Particle）"),
    "カラー" to ("Color" to "颜色"),
    "HSBカラーモード設定" to ("HSB color mode" to "HSB 颜色模式"),
    "グラデーション背景" to ("Gradient background" to "渐变背景"),
    "構造・クラス" to ("Structure & classes" to "结构与类"),
    "パーティクルクラス" to ("Particle class" to "粒子类"),
    "配列ループ更新" to ("Update an array" to "循环更新数组"),
    "インタラクション" to ("Interaction" to "交互"),
    "マウス・タッチ追従" to ("Mouse & touch tracking" to "鼠标与触摸跟随"),
    "タッチ押し込み判定" to ("Detect press or touch" to "检测按下或触摸"),
    "PNG画像書き出し" to ("Export PNG image" to "导出 PNG 图像"),
    "1x（通常）" to ("1x (normal)" to "1x（标准）"),
    "2x（高精細）" to ("2x (high resolution)" to "2x（高分辨率）"),
    "4x（超高精細）" to ("4x (ultra high resolution)" to "4x（超高分辨率）"),
    "2x・4xは再描画します。アニメーションや物理演算が進み、描き重ねの見た目が変わる場合があります。最大1600万画素。" to ("2x and 4x redraw the sketch. Animation and physics may advance; accumulated drawings may change. Limit: 16 million pixels." to "2x 和 4x 会重新绘制作品。动画和物理模拟可能推进，叠加绘图可能改变。上限为1600万像素。"),
    "オフスクリーンで高精細に再描画してPNG画像を保存します（最大1600万画素）。※アニメーションや乱数によりフレームが進む場合があります。" to ("Renders off-screen at high resolution to save a PNG image (up to 16 MP). ※ Animation or random frames may advance during redraw." to "在后台以高分辨率重新渲染并保存PNG图像（最高1600万像素）。※重新渲染可能使动画或随机帧发生推移。"),
    "− 現在のコード（削除） / + スナップショット（追加）" to ("− Current code (removed) / + Snapshot (added)" to "− 当前代码（删除）/ + 快照（新增）"),
    "録画を停止してから書き出してください" to ("Stop recording before exporting" to "请停止录制后再导出"),
    "%s × %s のPNG画像を保存しました" to ("Saved a %s × %s PNG image" to "已保存 %s × %s 的 PNG 图像"),
    "書き出し倍率が無効です" to ("Invalid export scale" to "导出倍率无效"),
    "再描画できる作品で録画を停止してから書き出してください" to ("Stop recording and use a sketch with a draw() function" to "请停止录制，并使用具有 draw() 函数的作品"),
    "画像が大きすぎます。倍率またはキャンバスサイズを下げてください" to ("Image too large. Reduce scale or canvas size." to "图像过大。请降低倍率或画布尺寸。"),
    "描画が完了してから再度お試しください" to ("Try again after drawing finishes" to "请在绘制完成后重试"),
    "指定した解像度で再描画できませんでした" to ("Could not redraw at the requested resolution" to "无法以指定分辨率重新绘制"),
    "カーソル位置に定番コードを挿入" to ("Insert common code at the cursor" to "在光标处插入常用代码"),
    "画像を書き出し中…" to ("Exporting image…" to "正在导出图像…"),
    "使い方ガイド" to ("User Guide" to "使用指南"),
    "更新履歴 (What's New)" to ("What's New" to "更新日志"),
    "ヘルプ" to ("Help" to "帮助"),
    "操作方法や機能の解説" to ("Learn features and shortcuts" to "功能与操作说明"),
    "パラメータ" to ("Parameters" to "参数"),
    "ライブパラメータ" to ("Live Parameters" to "实时参数"),
    "初期値" to ("Default" to "默认值"),
    "全て初期値に戻す" to ("Reset all" to "全部恢复默认"),
    "テンプレートをコピー" to ("Copy template" to "复制模板"),
    "テンプレートをコピーしました" to ("Template copied to clipboard" to "已复制模板到剪贴板"),
    "コードにパラメータ宣言を追加してください" to ("Add parameter declarations to your code" to "请在代码中添加参数声明"),
    "コードでは rinParams.speed と rinParams.ink を使います" to
        ("Use rinParams.speed and rinParams.ink in your code" to "在代码中使用 rinParams.speed 和 rinParams.ink"),
    "%s行目を展開" to ("Expand line %s" to "展开第%s行"),
    "%s行目を折りたたむ" to ("Fold line %s" to "折叠第%s行"),
    "現在のファイル" to ("Current file" to "当前文件"),
    "作品全体" to ("Entire work" to "整个作品"),
    "検索中…" to ("Searching…" to "正在搜索…"),
    "先頭%s件を表示" to ("Showing the first %s matches" to "显示前%s个结果"),
    "カスタム" to ("Custom" to "自定义"),
    "背景とアクセントカラーを設定" to ("Choose background and accent colors" to "设置背景和强调色"),
    "背景色" to ("Background color" to "背景色"),
    "アクセントカラー" to ("Accent color" to "强调色"),
    "6桁のカラーコード" to ("6-digit hex color" to "六位十六进制颜色"),
    "カラーピッカー" to ("Color picker" to "拾色器"),
    "カラーを編集" to ("Edit color" to "编辑颜色"),
    "カラーを挿入" to ("Insert color" to "插入颜色"),
    "カラーコード" to ("Color code" to "颜色代码"),
    "適用" to ("Apply" to "应用"),
    "挿入" to ("Insert" to "插入"),
    "色相" to ("Hue" to "色相"),
    "彩度" to ("Saturation" to "饱和度"),
    "明度" to ("Brightness" to "明度"),
    "不透明度" to ("Opacity" to "不透明度"),
    "プリセット" to ("Presets" to "预设"),
    "コンソール" to ("Console" to "控制台"),
    "コード" to ("Code" to "代码"),
    "実行" to ("Run" to "运行"),
    "作品設定" to ("Work settings" to "作品设置"),
    "追加ライブラリの読み込み順" to ("Additional library load order" to "附加库加载顺序"),
    "水彩・鉛筆の表現（p5.js 2.3.3 / WEBGL）" to ("Watercolor and pencils (p5.js 2.3.3 / WEBGL)" to "水彩和铅笔效果（p5.js 2.3.3 / WEBGL）"),
    "作品のライブラリ" to ("Work libraries" to "作品的库"),
    "p5.jsとライブラリを作品ごとに設定" to ("Set p5.js and libraries per work" to "为每个作品设置 p5.js 和库"),
    "共有の準備中" to ("Preparing to share" to "正在准备分享"),
    "録画を共有できませんでした。空き容量と録画ファイルを確認してください" to ("Could not share the recording. Check free storage and the recording file." to "无法分享录制文件。请检查可用空间和录制文件。"),
    "画像を共有できませんでした。空き容量とファイルを確認してください" to ("Could not share the image. Check free storage and the file." to "无法分享图像。请检查可用空间和文件。"),
    "録画設定" to ("Recording settings" to "录制设置"),
    "最大60秒の推定容量" to ("Estimated size for 60 seconds" to "60秒预计大小"),
    "容量は映像の内容や端末により変わります" to ("Size varies with content and device" to "大小因内容和设备而异"),
    "GIFは30fps・最大15秒。容量は映像によって変わります" to ("GIF: 30 fps, up to 15 seconds. Size varies with content." to "GIF：30帧/秒，最长15秒。大小因内容而异。"),
    "録画を開始" to ("Start recording" to "开始录制"),
    "残り時間" to ("Remaining" to "剩余时间"),
    "並び替え" to ("Sort" to "排序"),
    "作品プレビュー" to ("Work preview" to "作品预览"),
    "プレビュー未作成" to ("No preview yet" to "暂无预览"),
    "プレビュー" to ("Preview" to "预览"),
    "コンソールの高さを変更" to ("Resize console" to "调整控制台高度"),
    "変更内容を確認" to ("Review changes" to "查看更改"),
    "− 現在のコード / + 復元するコード" to ("− Current code / + Code to restore" to "− 当前代码 / + 要恢复的代码"),
    "最近開いた順" to ("Recently opened" to "最近打开"),
    "更新順" to ("Recently updated" to "最近更新"),
    "名前順" to ("Name" to "名称"),
    "保存中" to ("Saving" to "正在保存"),
    "作品ZIPを保存しました" to ("Work ZIP saved" to "作品 ZIP 已保存"),
    "作品ZIPを保存できませんでした" to ("Could not save work ZIP" to "无法保存作品 ZIP"),
    "作品ZIPを追加しました" to ("Work ZIP imported" to "已导入作品 ZIP"),
    "作品ZIPを読み込めませんでした" to ("Could not import work ZIP" to "无法导入作品 ZIP"),
    "作品ZIPを書き出す" to ("Export work ZIP" to "导出作品 ZIP"),
    "作品ZIPを追加" to ("Import work ZIP" to "导入作品 ZIP"),
    "読み込みコードを挿入" to ("Insert loading code" to "插入加载代码"),
    "この素材はプレビューできません" to ("Preview unavailable for this asset" to "无法预览此素材"),
    "円を描画" to ("Draw a circle" to "绘制圆形"),
    "四角形を描画" to ("Draw a rectangle" to "绘制矩形"),
    "楕円を描画" to ("Draw an ellipse" to "绘制椭圆"),
    "線を描画" to ("Draw a line" to "绘制直线"),
    "キャンバスの大きさ" to ("Canvas dimensions" to "画布尺寸"),
    "色を指定" to ("Set color" to "设置颜色"),
    "画像を読み込む" to ("Load an image" to "加载图像"),
    "画像を描画" to ("Draw an image" to "绘制图像"),
    "乱数を生成" to ("Generate a random number" to "生成随机数"),
    "数値の範囲を変換" to ("Map a numeric range" to "映射数值范围"),
    "座標を移動" to ("Translate coordinates" to "平移坐标"),
    "座標を回転" to ("Rotate coordinates" to "旋转坐标"),
    "文字を描画" to ("Draw text" to "绘制文本"),
    "p5.jsアカウント" to ("p5.js account" to "p5.js 账户"),
    "p5.js Web Editor" to ("p5.js Web Editor" to "p5.js Web Editor"),
    "p5.js Web Editorのユーザー名から公開作品を取り込みます。パスワードは使用しません。" to ("Import public sketches by p5.js Web Editor username. Your password is never used." to "通过 p5.js Web Editor 用户名导入公开作品，不使用密码。"),
    "ユーザー名" to ("Username" to "用户名"),
    "作品を取得" to ("Load works" to "获取作品"),
    "ユーザー名を入力して公開作品を取得してください" to ("Enter a username to load public works" to "输入用户名以获取公开作品"),
    "%s件の公開作品" to ("%s public works" to "%s 个公开作品"),
    "タップして取り込む" to ("Tap to import" to "点击导入"),
    "公開作品がありません" to ("No public works found" to "没有公开作品"),
    "p5.jsの作品を取得できませんでした" to ("Could not load p5.js works" to "无法获取 p5.js 作品"),
    "作品を取り込めませんでした。ファイル数・容量・通信環境を確認してください" to ("Could not import the work. Check its files, size, and your connection." to "无法导入作品，请检查文件数量、容量和网络连接。"),
    "p5.jsの作品を取り込みました" to ("p5.js work imported" to "已导入 p5.js 作品"),
    "アカウントの公開作品を選んで取り込みます" to ("Choose and import a public work from an account" to "从账户中选择并导入公开作品"),
    "p5.jsから作品を取り込む" to ("Import from p5.js" to "从 p5.js 导入作品"),
    "端末内" to ("On device" to "设备内"),
    "作品の素材" to ("Work assets" to "作品素材"),
    "画像・音声・フォントなどを管理" to ("Manage images, audio, fonts and more" to "管理图片、音频、字体等素材"),
    "画像・音声・動画・フォント・データを追加できます" to ("Add images, audio, video, fonts and data" to "可添加图片、音频、视频、字体和数据"),
    "1ファイル50MBまで、1作品200MB・100ファイルまで" to ("Up to 50 MB per file; 200 MB and 100 files per work" to "每个文件最多 50 MB，每个作品最多 200 MB、100 个文件"),
    "素材を追加すると、ここに表示されます" to ("Added assets will appear here" to "添加的素材将显示在这里"),
    "パスをコピー" to ("Copy path" to "复制路径"),
    "素材を追加" to ("Add assets" to "添加素材"),
    "素材を削除" to ("Delete asset" to "删除素材"),
    "ファイル名" to ("File name" to "文件名"),
    "コード内のパスも新しい名前に変更してください" to ("Also update the path in your code" to "请同时更新代码中的路径"),
    "素材を保存できませんでした" to ("Could not save assets" to "无法保存素材"),
    "素材を追加できませんでした。ファイル名・サイズ・保存先を確認してください" to ("Could not add assets. Check names, sizes and save location." to "无法添加素材，请检查文件名、大小和保存位置"),
    "ファイルを処理中…" to ("Processing files…" to "正在处理文件…"),

    "編集時にプレビューを隠す" to ("Hide preview while editing" to "编辑时隐藏预览"),
    "縦画面でコード欄を選ぶと非表示になり、編集を終えると戻ります" to ("In portrait, hide the preview when the code field is focused; restore it when editing ends" to "竖屏时选择代码区域隐藏预览，结束编辑后恢复"),
    "プレビューを隠す設定が優先されます" to ("Hide preview takes priority" to "优先隐藏预览"),
    "縦画面の編集中だけプレビューを低く表示します" to ("Use a shallow preview while editing in portrait" to "竖屏编辑时缩小预览高度"),

    "アップデート" to ("Updates" to "更新"),
    "アップデートを確認" to ("Check for updates" to "检查更新"),
    "確認中…" to ("Checking…" to "正在检查…"),
    "新しいバージョンがあります" to ("A new version is available" to "有新版本可用"),
    "新しいアップデートはありません" to ("No new updates available" to "暂无新更新"),
    "公開済みのバージョンが見つかりません" to ("No published version found" to "未找到已发布的版本"),
    "バージョンを比較できませんでした" to ("Unable to compare versions" to "无法比较版本"),
    "確認できませんでした。通信環境を確認して、もう一度お試しください" to ("Couldn't check for updates. Check your connection and try again." to "无法检查更新。请检查网络连接后重试"),
    "配布ページを開く" to ("Open release page" to "打开发布页面"),
    "ブラウザーを開けませんでした" to ("Couldn't open a browser" to "无法打开浏览器"),
    "ライセンス情報" to ("License information" to "许可证信息"),
    "アプリ情報とリンク" to ("App information and links" to "应用信息与链接"),
    "アプリ情報" to ("App information" to "应用信息"),
    "バージョン %s" to ("Version %s" to "版本 %s"),
    "開発者" to ("Developer" to "开发者"),
    "サポート" to ("Support" to "支持"),
    "開発を任意で支援できます" to ("Optionally support development" to "可自愿支持开发"),
    "アプリのフォント" to ("App font" to "应用字体"),
    "標準フォント" to ("Default font" to "默认字体"),
    "TTF・OTF・TTCをインポート。設定画面とエディターに反映します" to ("Import TTF, OTF or TTC for the interface and editor" to "导入 TTF、OTF 或 TTC，应用于界面和编辑器"),
    "フォントをインポート" to ("Import font" to "导入字体"),
    "読み込み中" to ("Loading" to "正在加载"),
    "標準に戻す" to ("Use default" to "恢复默认"),
    "フォントの連字" to ("Ligatures" to "连字"),
    "対応フォントの連字を有効にします。コードの文字列は変わりません" to ("Enable ligatures in supported fonts. Code text is unchanged." to "启用字体支持的连字，不更改代码文本。"),
    "フォントを読み込めません。20MB以下のTTF・OTF・TTCを選んでください" to ("Could not load font. Choose a TTF, OTF or TTC up to 20 MB." to "无法加载字体。请选择不超过 20 MB 的 TTF、OTF 或 TTC。"),
    "反射するEDIT:RiNのテンプレート" to ("Bouncing EDIT:RiN template" to "EDIT:RiN 反弹模板"),
    "描画の縦横を切り替える" to ("Swap canvas width and height" to "切换画布横竖方向"),
    "録画を停止してから描画の向きを変更してください" to ("Stop recording before changing canvas orientation" to "请先停止录屏再更改画布方向"),
    "描画の向きを変更できませんでした" to ("Could not change canvas orientation" to "无法更改画布方向"),
    "%s作品" to ("%s works" to "%s 个作品"),
    "%s を入力" to ("Insert %s" to "输入 %s"),
    "プレビュー比率を変更: %s" to ("Change preview ratio: %s" to "更改预览比例：%s"),
    "%s件" to ("%s matches" to "%s 个匹配项"),
    "「%s」を削除しますか？" to ("Delete ‘%s’?" to "删除“%s”？"),
    "閉じる" to ("Close" to "关闭"),
    "作品・未保存" to ("Work · Unsaved" to "作品 · 未保存"),
    "作品" to ("Work" to "作品"),
    "作品を選択" to ("Select a work" to "选择作品"),
    "作品一覧を開く" to ("Open works" to "打开作品列表"),
    "追加" to ("Add" to "添加"),
    "作品名で検索" to ("Search by name" to "按名称搜索"),
    "検索をクリア" to ("Clear search" to "清除搜索"),
    "一致する作品がありません" to ("No matching works" to "没有匹配的作品"),
    "、選択中" to (", selected" to "，已选中"),
    "未保存" to ("Unsaved" to "未保存"),
    "未保存の変更あり" to ("Unsaved changes" to "有未保存的更改"),
    "選択中" to ("Selected" to "已选中"),
    "タップして開く" to ("Tap to open" to "点击打开"),
    "編集・作品" to ("Edit & work" to "编辑与作品"),
    "元に戻す" to ("Undo" to "撤销"),
    "直前の編集を取り消す" to ("Undo the last edit" to "撤销上一次编辑"),
    "やり直す" to ("Redo" to "重做"),
    "取り消した編集をやり直す" to ("Redo the undone edit" to "重做已撤销的编辑"),
    "検索・置換" to ("Find & replace" to "查找与替换"),
    "文字列検索、置換、指定行へ移動" to ("Find, replace, or go to a line" to "查找、替换或跳转到指定行"),
    "コードを整形" to ("Format code" to "格式化代码"),
    "インデントと空行を整理" to ("Tidy indentation and blank lines" to "整理缩进和空行"),
    "プロジェクトファイル" to ("Project files" to "项目文件"),
    "実行環境" to ("Runtime" to "运行环境"),
    "p5.jsとp5.soundを作品ごとに設定" to ("Set p5.js and p5.sound for this work" to "为此作品设置 p5.js 和 p5.sound"),
    "p5.jsバージョン" to ("p5.js version" to "p5.js 版本"),
    "現在の標準" to ("Current" to "当前标准"),
    "旧作品向け" to ("Legacy" to "旧作品"),
    "音声再生・合成・解析を有効にします" to ("Enable audio playback, synthesis, and analysis" to "启用音频播放、合成和分析"),
    "実行環境を保存できませんでした" to ("Could not save runtime settings" to "无法保存运行环境设置"),
    "追加JavaScriptファイルを管理" to ("Manage supporting JavaScript files" to "管理附加 JavaScript 文件"),
    "変更履歴" to ("Revision history" to "修改历史"),
    "過去30回の保存状態を表示・復元" to ("View or restore the last 30 revisions" to "查看或恢复最近 30 次保存的版本"),
    "プレビュー比率" to ("Preview aspect ratio" to "预览比例"),
    "作品ごとにキャンバスの縦横比を設定" to ("Set the canvas aspect ratio for this work" to "设置此作品的画布比例"),
    "名前を変更" to ("Rename" to "重命名"),
    "作品タイトルを編集" to ("Edit the work name" to "编辑作品名称"),
    "複製" to ("Duplicate" to "复制作品"),
    "現在のコードからコピーを作成" to ("Create a copy of the current code" to "创建当前代码的副本"),
    "JSをインポート" to ("Import JS" to "导入 JS"),
    "外部のJavaScriptファイルを読み込む" to ("Open an external JavaScript file" to "读取外部 JavaScript 文件"),
    "JSを書き出す" to ("Export JS" to "导出 JS"),
    "現在の作品を.jsファイルとして保存" to ("Save the current work as a .js file" to "将当前作品保存为 .js 文件"),
    "削除" to ("Delete" to "删除"),
    "この作品を削除" to ("Delete this work" to "删除此作品"),
    "最後の1作品は削除できません" to ("The last work cannot be deleted" to "无法删除最后一个作品"),
    "画面を回転" to ("Rotate screen" to "旋转屏幕"),
    "設定" to ("Settings" to "设置"),
    "作品を追加" to ("Add a work" to "添加作品"),
    "作品メニュー" to ("Work menu" to "作品菜单"),
    "作品未選択" to ("No work selected" to "未选择作品"),
    " · 未保存" to (" · Unsaved" to " · 未保存"),
    "管理" to ("Manage" to "管理"),
    "スクリーンショットをPictures/EditRiNへ保存しました" to ("Screenshot saved to Pictures/EditRiN" to "截图已保存到 Pictures/EditRiN"),
    "スクリーンショットを保存できませんでした" to ("Could not save the screenshot" to "无法保存截图"),
    "シェアカードを作成" to ("Create share card" to "创建分享卡片"),
    "シェアカード設定" to ("Share Card Settings" to "分享卡片设置"),
    "シェアカード" to ("Share Card" to "分享卡片"),
    "スクリーンショット" to ("Screenshot" to "截图"),
    "シェアカードをPictures/EditRiNへ保存しました" to ("Share card saved to Pictures/EditRiN" to "分享卡片已保存到 Pictures/EditRiN"),
    "シェアカードを保存できませんでした" to ("Could not save share card" to "无法保存分享卡片"),
    "QRコードを含める" to ("Include QR code" to "包含二维码"),
    "カメラ等でスキャンしてブラウザで作品を実行できます" to ("Scan to run this sketch live in browser" to "可通过扫描二维码在浏览器中运行作品"),
    "Webのコード表示ボタン" to ("Web code button" to "网页代码按钮"),
    "OFFで表示ボタンを隠します。コードはリンクに含まれるため、非公開にはなりません" to
        ("OFF hides the code button. The link still contains the code, so it remains accessible." to
        "关闭后将隐藏代码按钮。链接仍包含代码，因此代码并非私密。"),
    "⚠️ 作品に画像・音声などの外部素材が含まれているため、QRコードでのWeb実行は利用できません。プレビューとコードのみのカードを作成します。" to
        ("⚠️ QR code execution is unavailable because external assets (images, audio, etc.) are used. Creating a card with preview and code only." to
        "⚠️ 由于作品包含图片、音频等外部素材，无法通过二维码在网页运行。将仅生成包含预览与代码的卡片。"),
    "⚠️ コード容量がQRコードの上限を超えているため、QRコードを含められません。プレビューとコードのみのカードを作成します。" to
        ("⚠️ QR code cannot be included because the code size exceeds the capacity limit. Creating a card with preview and code only." to
        "⚠️ 代码量超过二维码容量上限，无法包含二维码。将仅生成包含预览与代码的卡片。"),
    "ソースコードを掲載" to ("Include source code" to "包含源代码"),
    "カード内にコードスニペットを表示します" to ("Display code snippet on the card" to "在卡片内展示代码片段"),
    "掲載範囲: %d 〜 %d 行目 (全 %d 行)" to ("Lines: %d - %d (Total: %d lines)" to "展示范围：%d ~ %d 行（共 %d 行）"),
    "開始:" to ("Start:" to "起始:"),
    "終了:" to ("End:" to "结束:"),
    "カードを端末に保存" to ("Save card to device" to "保存卡片到设备"),
    "ミッドナイト" to ("Midnight" to "午夜蓝"),
    "サイバー" to ("Cyber" to "赛博"),
    "作者クレジット（任意）" to ("Author credit (optional)" to "作者署名（可选）"),
    "例: @username" to ("e.g. @username" to "例如: @username"),
    "MP4をMovies/EditRiNへ保存しました" to ("MP4 saved to Movies/EditRiN" to "MP4 已保存到 Movies/EditRiN"),
    "GIFをPictures/EditRiNへ保存しました" to ("GIF saved to Pictures/EditRiN" to "GIF 已保存到 Pictures/EditRiN"),
    "録画をMovies/EditRiNへ保存しました" to ("Recording saved to Movies/EditRiN" to "录屏已保存到 Movies/EditRiN"),
    "録画を保存できませんでした" to ("Could not save the recording" to "无法保存录屏"),
    "録画形式を選択" to ("Choose recording format" to "选择录制格式"),
    "MP4は30fps・最大60秒、GIFは30fps・最大15秒で保存します" to ("MP4 records at 30 fps for up to 60 seconds; GIF records at 30 fps for up to 15 seconds" to "MP4 以 30 fps 最长录制 60 秒；GIF 以 30 fps 最长录制 15 秒"),
    "残り %s" to ("%s remaining" to "剩余 %s"),
    "保存した録画" to ("Saved recording" to "已保存的录屏"),
    "開く" to ("Open" to "打开"),
    "共有" to ("Share" to "分享"),
    "Xで共有" to ("Share to X" to "分享到 X"),
    "録画を開けませんでした" to ("Could not open the recording" to "无法打开录屏"),
    "共有できませんでした" to ("Could not share the recording" to "无法分享录屏"),
    "Xアプリを開けないため共有先を選択してください" to ("X could not be opened; choose another app" to "无法打开 X，请选择其他应用"),
    "録画と共有" to ("Recording and sharing" to "录制与分享"),
    "MP4ビットレート" to ("MP4 bitrate" to "MP4 比特率"),
    "高い値ほど画質とファイルサイズが大きくなります" to ("Higher values increase quality and file size" to "数值越高，画质和文件大小越大"),
    "録画開始カウントダウン" to ("Recording countdown" to "录制倒计时"),
    "なし" to ("Off" to "关闭"),
    "%s秒" to ("%s sec" to "%s 秒"),
    "X共有の定型文" to ("Default X post text" to "X 分享默认文本"),
    "Xで共有するときに録画と一緒に入力します" to ("Added with the recording when sharing to X" to "分享到 X 时与录屏一起填入"),
    "初期値に戻す" to ("Restore default" to "恢复默认值"),
    "録画カウントダウンを中止" to ("Cancel recording countdown" to "取消录制倒计时"),
    "プレビューをスクリーンショット" to ("Capture preview" to "截取预览"),
    "録画を停止" to ("Stop recording" to "停止录屏"),
    "プレビューを録画" to ("Record preview" to "录制预览"),
    "プレビューを全画面表示" to ("Full-screen preview" to "全屏预览"),
    "全画面表示を閉じる" to ("Exit full screen" to "退出全屏"),
    "録画を停止してから全画面表示を閉じてください" to ("Stop recording before exiting full screen" to "请先停止录屏再退出全屏"),
    "プレビュー操作を閉じる" to ("Close preview controls" to "关闭预览控件"),
    "プレビュー操作を開く" to ("Open preview controls" to "打开预览控件"),
    "再生" to ("Play" to "播放"),
    "一時停止" to ("Pause" to "暂停"),
    "再読み込み" to ("Reload" to "重新加载"),
    "ログ" to ("Console" to "日志"),
    "保存済み状態に戻す" to ("Revert to saved" to "恢复到已保存状态"),
    "作品を保存" to ("Save work" to "保存作品"),
    "ログはありません" to ("No messages" to "暂无日志"),
    "検索と置換" to ("Find and replace" to "查找与替换"),
    "インデント" to ("Indent" to "增加缩进"),
    "インデントを戻す" to ("Outdent" to "减少缩进"),
    "左へ移動" to ("Move left" to "向左移动"),
    "上へ移動" to ("Move up" to "向上移动"),
    "下へ移動" to ("Move down" to "向下移动"),
    "右へ移動" to ("Move right" to "向右移动"),
    "コメントを入力" to ("Insert comment" to "插入注释"),
    "プレビューとエディターの分割を調整" to ("Adjust preview/editor split" to "调整预览与编辑器分隔"),
    "プレビューを広げる" to ("Expand preview" to "扩大预览"),
    "エディターを広げる" to ("Expand editor" to "扩大编辑器"),
    "空のコード" to ("Empty code" to "空代码"),
    "正方形" to ("Square" to "正方形"),
    "標準・横" to ("Standard landscape" to "标准横向"),
    "ワイド" to ("Wide" to "宽屏"),
    "縦長" to ("Portrait" to "纵向"),
    "編集" to ("Edit" to "编辑"),
    "ファイルを追加" to ("Add file" to "添加文件"),
    "JSファイルを追加" to ("Add JS file" to "添加 JS 文件"),
    "JSファイルを編集" to ("Edit JS file" to "编辑 JS 文件"),
    "ファイルを編集" to ("Edit file" to "编辑文件"),
    "ファイル名（.js）" to ("File name (.js)" to "文件名（.js）"),
    "ファイル名（.js / .frag / .vert）" to ("File name (.js / .frag / .vert)" to "文件名（.js / .frag / .vert）"),
    "JavaScriptコード" to ("JavaScript code" to "JavaScript 代码"),
    "シェーダーコード" to ("Shader code" to "着色器代码"),
    "追加ファイルは名前順にsketch.jsより先に実行されます。" to ("Supporting files run in name order before sketch.js." to "附加文件按名称顺序在 sketch.js 之前执行。"),
    "シェーダーは loadShader() や rinShaders で読み込み可能です。" to ("Shaders can be loaded via loadShader() or rinShaders." to "着色器可通过 loadShader() 或 rinShaders 加载。"),
    "2D物理演算エンジン（剛体・重力・衝突）" to ("2D physics engine (rigid bodies, gravity, collision)" to "2D物理引擎（刚体、重力、碰撞）"),
    "スナップショットを読み込み中…" to ("Loading snapshots…" to "正在加载快照…"),
    "スナップショットを処理中…" to ("Processing snapshots…" to "正在处理快照…"),
    "スナップショットを読み込めませんでした。既存の記録は上書きしません。" to ("Could not load snapshots. Existing history will not be overwritten." to "无法加载快照。不会覆盖现有记录。"),
    "スナップショットを保存できませんでした。編集内容は保持されています。" to ("Could not save the snapshot. Your edits are preserved." to "无法保存快照。编辑内容已保留。"),
    "復元を保存できませんでした。元の編集内容は保持されています。" to ("Could not save the restored state. Your previous edits are preserved." to "无法保存恢复状态。原有编辑内容已保留。"),
    "スナップショットを削除できませんでした。" to ("Could not delete the snapshot." to "无法删除快照。"),
    "再試行" to ("Retry" to "重试"),
    "スナップショット" to ("Snapshots" to "快照"),
    "スナップショット（一時保存）" to ("Snapshots (Checkpoints)" to "快照（临时保存）"),
    "状態の記録・復元" to ("Save and restore states" to "保存与恢复状态"),
    "現在の状態をスナップショット（保存）" to ("Snapshot current state" to "快照当前状态"),
    "保存されたスナップショットはありません" to ("No snapshots saved yet" to "尚无已保存的快照"),
    "（現在）" to (" (Current)" to "（当前）"),
    "スナップショットを記録しました" to ("Snapshot saved" to "已保存快照"),
    "スナップショットに復元しました" to ("Restored to snapshot" to "已恢复至快照"),
    "スナップショットを削除" to ("Delete snapshot" to "删除快照"),
    "このスナップショットを削除しますか？この操作は取り消せません。" to ("Delete this snapshot? This cannot be undone." to "确定删除此快照吗？此操作无法撤销。"),
    "− 現在のコード / + スナップショットのコード" to ("− Current code / + Snapshot code" to "− 当前代码 / + 快照代码"),
    "この状態に復元" to ("Restore this state" to "恢复到此状态"),
    "差分を確認" to ("View diff" to "查看差异"),
    "行" to ("lines" to "行"),
    "ファイル" to ("files" to "文件"),
    "コードを画面幅で折り返す" to ("Wrap code at screen width" to "自动换行以适应屏幕宽度"),
    "長い行を画面幅に合わせて下段に折り返します" to ("Wrap long lines to fit screen width" to "长行将自动折行以适应屏幕宽度"),
    "折り返さずに1行で表示し、横スクロールできるようにします" to ("Display as single line with horizontal scroll without wrapping" to "单行显示不换行，支持横向滚动"),
    "横画面の配置（エディターを左）" to ("Landscape layout (Editor on left)" to "横屏布局（编辑器居左）"),
    "左にエディター、右にプレビューを表示します" to ("Display editor on left, preview on right" to "左侧显示编辑器，右侧显示预览"),
    "左にプレビュー、右にエディターを表示します（従来）" to ("Display preview on left, editor on right (Legacy)" to "左侧显示预览，右侧显示编辑器（经典）"),
    "スクショ" to ("Screenshot" to "截屏"),
    "録画" to ("Record" to "录制"),
    "録画停止" to ("Stop recording" to "停止录制"),
    "録画中止" to ("Cancel recording" to "取消录制"),
    "プレビュー操作" to ("Preview controls" to "预览控制"),
    "全画面" to ("Fullscreen" to "全屏"),
    "過去の保存状態を表示・復元" to ("View or restore past saved revisions" to "查看并恢复历史保存记录"),
    "描画プロセスが異常終了しました（メモリまたはGPU負荷が高すぎる可能性があります）" to ("Render process terminated abnormally (memory or GPU load may be too high)" to "渲染进程异常终止（内存或GPU负载可能过高）"),
    "描画プロセスがメモリ不足等により終了されました" to ("Render process was terminated due to low memory" to "渲染进程因内存不足等原因终止"),
    "保存" to ("Save" to "保存"),
    "キャンセル" to ("Cancel" to "取消"),
    "検索する文字列" to ("Find text" to "查找内容"),
    "大文字・小文字を区別" to ("Match case" to "区分大小写"),
    "0件" to ("0 matches" to "0 个匹配项"),
    "前へ" to ("Previous" to "上一个"),
    "次へ" to ("Next" to "下一个"),
    "置換後の文字列" to ("Replace with" to "替换为"),
    "置換" to ("Replace" to "替换"),
    "すべて置換" to ("Replace all" to "全部替换"),
    "行番号" to ("Line numbers" to "行号"),
    "移動" to ("Go" to "跳转"),
    "作品フォルダーを選択" to ("Choose work folder" to "选择作品文件夹"),
    "作品は選択したフォルダーに保存されます。再インストール後も同じフォルダーを選択すれば復元できます。" to ("Works are saved in this folder. Select it again after reinstalling to restore them." to "作品保存在所选文件夹中。重新安装后选择同一文件夹即可恢复。"),
    "フォルダーを選択" to ("Choose folder" to "选择文件夹"),
    "新しい作品" to ("New work" to "新作品"),
    "名前と描画比率を選んでスタート" to ("Choose a name and aspect ratio" to "选择名称和画布比例"),
    "作品名" to ("Work name" to "作品名称"),
    "描画比率" to ("Canvas aspect ratio" to "画布比例"),
    "端末" to ("Device" to "设备"),
    "端末・横" to ("Device (Landscape)" to "设备（横向）"),
    "端末・縦" to ("Device (Portrait)" to "设备（纵向）"),
    "端末の画面比率" to ("Device screen ratio" to "设备屏幕比例"),
    "横向きの端末比率" to ("Landscape device ratio" to "横向设备比例"),
    "縦向きの端末比率" to ("Portrait device ratio" to "纵向设备比例"),
    "端末の向きに合わせて比率が切り替わります" to ("The ratio follows the device orientation" to "比例会随设备方向切换"),
    "作品の表示枠を選択" to ("Choose the work frame" to "选择作品显示框"),
    "キャンバスの動作" to ("Canvas behavior" to "画布行为"),
    "固定サイズ" to ("Fixed size" to "固定尺寸"),
    "画面に合わせる" to ("Fit to screen" to "适应屏幕"),
    "指定した描画サイズを維持し、表示だけを枠に合わせます" to ("Keep the specified canvas size and fit only its display" to "保持指定的画布尺寸，仅调整显示以适应预览框"),
    "作業領域に合わせてresizeCanvas()を実行します" to ("Run resizeCanvas() when the workspace changes" to "工作区域变化时执行 resizeCanvas()"),
    "シンプルな円のテンプレート" to ("Simple circle template" to "简单圆形模板"),
    "選択した比率を作品に保存します。現在の作品のコードはコピーしません。" to ("The ratio is saved with the work. Existing code is not copied." to "所选比例将保存到作品中，不会复制当前代码。"),
    "作成" to ("Create" to "创建"),
    "作品名を変更" to ("Rename work" to "重命名作品"),
    "変更" to ("Apply" to "应用"),
    "作品を削除" to ("Delete work" to "删除作品"),
    "戻る" to ("Back" to "返回"),
    "外観" to ("Appearance" to "外观"),
    "エディター" to ("Editor" to "编辑器"),
    "保存とバックアップ" to ("Storage" to "存储"),
    "テーマとシステムUI" to ("Theme and system UI" to "主题与系统界面"),
    "テーマ" to ("Theme" to "主题"),
    "端末の設定とMaterial Youに合わせます" to ("Follow device settings and Material You" to "跟随设备设置与 Material You"),
    "黒を基調とした表示" to ("Black-based appearance" to "黑色主题"),
    "白を基調とした表示" to ("White-based appearance" to "白色主题"),
    "自動" to ("System" to "跟随系统"),
    "ダーク" to ("Dark" to "深色"),
    "ライト" to ("Light" to "浅色"),
    "ログをすべてコピー" to ("Copy all logs" to "复制所有日志"),
    "ログをコピー" to ("Copy log" to "复制日志"),
    "ログを消去" to ("Clear logs" to "清除日志"),
    "ステータスバーを非表示" to ("Hide status bar" to "隐藏状态栏"),
    "ナビゲーションバーを非表示" to ("Hide navigation bar" to "隐藏导航栏"),
    "横画面では両方のバーが常に非表示になります" to ("Both bars are always hidden in landscape" to "横屏时始终隐藏两个栏"),
    "ステータスバーを表示" to ("Show status bar" to "显示状态栏"),
    "ナビゲーションバーを表示" to ("Show navigation bar" to "显示导航栏"),
    "時刻と通知アイコンの表示を切り替えます" to ("Toggle the clock and notification icons" to "切换时钟和通知图标的显示"),
    "OSの戻る・ホーム・アプリ切替バーの表示を切り替えます" to ("Toggle the system navigation bar" to "切换系统导航栏的显示"),
    "ステータスバー" to ("Status bar" to "状态栏"),
    "ステータスバーとナビゲーションバーを非表示" to ("Hide status bar and navigation bar" to "隐藏状态栏与导航栏"),
    "横画面では自動的に非表示になります" to ("Automatically hidden in landscape" to "横屏时自动隐藏"),
    "横画面では常に全画面（非表示）になります" to ("Always full screen (hidden) in landscape" to "横屏时始终全屏（隐藏）"),
    "時刻、通知アイコン、OSナビゲーションバーを非表示にして画面を広く使います" to ("Hide system status and navigation bars for more screen space" to "隐藏系统状态栏与导航栏以获得更大屏幕空间"),
    "時刻や通知アイコンを表示します" to ("Show time and notification icons" to "显示时间和通知图标"),
    "横画面でノッチ部分まで使用" to ("Use cutout area in landscape" to "横屏时使用刘海区域"),
    "余白なしで表示します。ノッチの位置は内容が隠れる場合があります" to ("Use the full width. The cutout may obscure content." to "使用全部宽度。刘海可能遮挡内容。"),
    "ノッチを避ける余白を確保します" to ("Keep content clear of the cutout" to "保留避开刘海的边距"),
    "画面の向きを固定" to ("Disable automatic rotation" to "关闭自动旋转"),
    "自動回転を停止し、上部の↻ボタンで縦横を切り替えます" to ("Use the top rotate button instead of automatic rotation" to "使用顶部旋转按钮切换方向"),
    "端末の向きに合わせて画面を回転します" to ("Rotate with the device" to "跟随设备方向旋转"),
    "編集とプレビューの動作" to ("Editing and preview behavior" to "编辑与预览行为"),
    "作品切替時に自動実行" to ("Run when switching works" to "切换作品时自动运行"),
    "作品を選択するとプレビューを更新します" to ("Update the preview when a work is selected" to "选择作品时更新预览"),
    "編集時にプレビューを縮小" to ("Compact preview while editing" to "编辑时缩小预览"),
    "縦画面の編集中は横幅いっぱいの浅いプレビューに切り替えます。作品の保存比率は変更しません" to ("Use a shallow full-width preview while editing in portrait, without changing the saved ratio." to "竖屏编辑时使用全宽的低矮预览，不更改已保存比例。"),
    "サイズ調整バー" to ("Resize divider" to "尺寸调整分隔线"),
    "プレビューとエディターの間にドラッグ操作を表示します" to ("Show a draggable divider between preview and editor" to "显示预览与编辑器之间的可拖动分隔线"),
    "境界線とドラッグ操作を非表示にします" to ("Hide the divider and disable dragging" to "隐藏分隔线并禁用拖动"),
    "横画面のプレビュー幅" to ("Landscape preview width" to "横屏预览宽度"),
    "プレビューに使う横幅を調整します" to ("Adjust the space allocated to preview and editor" to "调整预览与编辑器占用的空间"),
    "全画面でも描画サイズを維持" to ("Preserve work size in full screen" to "全屏时保持作品尺寸"),
    "通常プレビューと同じ座標・縦横比で実行し、表示だけを拡大します" to ("Keep preview coordinates and ratio; scale only the display" to "保持预览坐标和比例，仅放大显示"),
    "自動インデント" to ("Auto indent" to "自动缩进"),
    "改行時に現在の字下げを引き継ぎ、括弧内を一段下げます" to ("Carry indentation to new lines and indent inside braces" to "换行时保留缩进，并在括号内增加一级"),
    "コードの各行に番号を表示します" to ("Show a number for each code line" to "为每行代码显示行号"),
    "編集キー" to ("Keyboard toolbar" to "键盘工具栏"),
    "編集中にTAB、カーソル移動、記号ボタンを表示します" to ("Show TAB, cursor and symbol buttons while editing" to "编辑时显示 TAB、光标和符号按钮"),
    "入力候補" to ("p5.js suggestions" to "p5.js 输入建议"),
    "p5.jsの関数名や変数名の候補を表示します" to ("Suggest p5.js function and built-in variable names" to "显示 p5.js 函数名和内置变量名"),
    "移動キーを表示" to ("Show navigation keys" to "显示导航键"),
    "操作パネルにTABとカーソルキーを表示します" to ("Show TAB and arrow keys in the toolbar" to "在工具栏中显示 TAB 和方向键"),
    "記号キーを表示" to ("Show symbol keys" to "显示符号键"),
    "操作パネルに括弧や記号キーを表示します" to ("Show brackets and symbols in the toolbar" to "在工具栏中显示括号和符号键"),
    "編集キーを小さくする" to ("Compact keys" to "紧凑按键"),
    "操作パネルの高さとキー幅を小さくします" to ("Reduce toolbar height and key width" to "减小工具栏高度和按键宽度"),
    "未保存のコードを復元" to ("Recover unsaved edits" to "恢复未保存的编辑"),
    "未保存の変更を一時保存し、次回起動時に復元します" to ("Keep a draft and restore it on next launch" to "暂存未保存的更改并在下次启动时恢复"),
    "アプリを離れるときに自動保存" to ("Auto-save when leaving the app" to "离开应用时自动保存"),
    "別のアプリへ切り替えたとき、編集中の作品を自動で保存します" to ("Saves the work you are editing when you switch to another app" to "切换到其他应用时自动保存正在编辑的作品"),
    "現在値をコードの初期値に反映しました" to ("Current values written to the code as defaults" to "已将当前值写入代码作为初始值"),
    "現在値を初期値にする" to ("Set as defaults" to "设为初始值"),
    "記録・表示" to ("Records & view" to "记录与显示"),
    "作品の整理" to ("Organize work" to "整理作品"),
    "テンプレート・ピン・タグ・名前・複製" to ("Templates, pin, tags, rename, duplicate" to "模板、置顶、标签、重命名、复制"),
    "作品の整理に使う操作" to ("Actions for organizing this work" to "用于整理作品的操作"),
    "録画の画質と共有時の定型文" to ("Recording quality and share text" to "录制画质与分享文案"),
    "書き出し" to ("Export" to "导出"),
    "文字サイズ" to ("Font size" to "字号"),
    "コードエディターの文字サイズ" to ("Code editor font size" to "代码编辑器字号"),
    "保存先とファイル入出力" to ("Save location and file transfer" to "保存位置与文件导入导出"),
    "作品フォルダー" to ("Work folder" to "作品文件夹"),
    "保存先を変更" to ("Change folder" to "更改文件夹"),
    "JavaScriptファイル" to ("JavaScript files" to "JavaScript 文件"),
    ".js を作品として読み込む、または現在のコードを書き出します" to ("Import a .js file as a work or export the current code" to "将 .js 文件导入为作品，或导出当前代码"),
    "作品と設定のバックアップ" to ("Full backup" to "完整备份"),
    "すべての作品とエディター設定をZIPで保存・復元します" to ("Save or restore all works and editor settings as ZIP" to "以 ZIP 保存或恢复所有作品和编辑器设置"),
    "復元" to ("Restore" to "恢复"),
    "ZIP保存" to ("Save ZIP" to "保存 ZIP"),
    "未選択" to ("Not selected" to "未选择"),
    "選択済みフォルダー" to ("Selected folder" to "已选文件夹"),
    "言語" to ("Language" to "语言"),
    "アプリの表示言語" to ("App display language" to "应用显示语言"),
    "システムデフォルト" to ("System default" to "跟随系统"),
    "対応していない端末言語の場合は英語を使用します" to ("Unsupported device languages use English" to "不支持的设备语言将使用英语"),
    "保存先を作成できませんでした" to ("Could not create the destination" to "无法创建保存位置"),
    "保存先を開けませんでした" to ("Could not open the destination" to "无法打开保存位置"),
    "保存先を利用できません" to ("Destination unavailable" to "保存位置不可用"),
    "保存できませんでした。保存先を確認して再試行してください" to ("Could not save. Check the folder and retry." to "无法保存。请检查文件夹后重试。"),
    "比率を保存できませんでした。保存先を確認してください" to ("Could not save the ratio. Check the folder." to "无法保存比例。请检查文件夹。"),
    "録画を停止してから再実行してください" to ("Stop recording before running again" to "请先停止录屏再重新运行"),
    "保存できませんでした。保存先フォルダーを確認してください" to ("Could not save. Check the destination folder." to "无法保存。请检查目标文件夹。"),
    "作品ファイルを読み込めません。元のファイルは上書きしていません" to ("Could not read works. The original file was not overwritten." to "无法读取作品。原文件未被覆盖。"),
    "JSファイルを読み込めませんでした" to ("Could not import JS" to "无法导入 JS"),
    "JSファイルを書き出せませんでした" to ("Could not export JS" to "无法导出 JS"),
    "バックアップを書き出せませんでした" to ("Could not export backup" to "无法导出备份"),
    "バックアップを復元できませんでした" to ("Could not restore backup" to "无法恢复备份"),
    "作品を保存できませんでした。保存先を確認してください" to ("Could not save the work. Check the folder." to "无法保存作品。请检查文件夹。"),
    "保存先フォルダーにアクセスできません" to ("Cannot access the folder" to "无法访问文件夹"),
    "保存先フォルダーを読み込めません" to ("Cannot read the folder" to "无法读取文件夹"),
    "作品ファイルを読み込めません" to ("Cannot read the work file" to "无法读取作品文件"),
    "作品ファイルの形式を読み取れません" to ("Invalid work file format" to "作品文件格式无效"),
    "Edit:RiN へようこそ" to ("Welcome to Edit:RiN" to "欢迎使用 Edit:RiN"),
    "作品コードや画像・音声アセットを安全に保存し、バックアップや外部ファイル管理アプリと連携するために、作品の保存先フォルダーを選択してください。" to
        ("Please choose a works folder to safely store your code, images, and audio assets, and to easily backup or sync with external file apps." to "请选择作品保存文件夹，以便安全存储代码、图像和音频素材，并方便备份或与外部文件管理应用同步。"),
    "※「Documents」などに「Edit-RiN」フォルダーを新規作成して選択するのがおすすめです。既存の作品フォルダーがある場合はそれを選択すると復元されます。" to
        ("※ We recommend creating a new 'Edit-RiN' folder in 'Documents'. If you already have an existing works folder, selecting it will restore your works." to "※ 建议在“Documents”中新建“Edit-RiN”文件夹并选择。如果您已有作品文件夹，选择它即可恢复作品。"),
    "保存先フォルダーを選択" to ("Choose works folder" to "选择作品文件夹"),
    "あとで設定（端末内に保存）" to ("Set up later (save on device)" to "稍后设置（保存在设备内）"),
    "新しいサンプル作品の追加" to ("Add new sample works" to "添加新样例作品"),
    "新しく追加された公式サンプル（%s）を現在の作品フォルダーに追加しますか？\n\n※既存の作品はそのまま保持されます。" to
        ("Would you like to add the new official samples (%s) to your works folder?\n\n※ Existing works will be kept unchanged." to "是否将新增的官方样例（%s）添加到当前作品文件夹？\n\n※ 现有作品将完整保留。"),
    "作品一覧に追加" to ("Add to works" to "添加到作品列表"),
    "あとで" to ("Later" to "稍后"),
    "サンプル作品を追加しました" to ("Sample works added" to "已添加样例作品"),
    "公式サンプル作品を追加" to ("Add official sample works" to "添加官方样例作品"),
    "すべての公式サンプル作品は既に追加されています" to ("All official sample works are already added" to "所有官方样例作品已添加"),
    "公式サンプル作品（%s件）を追加しました" to ("Added %s official sample work(s)" to "已添加 %s 个官方样例作品"),
    "ピン留め" to ("Pin" to "置顶"),
    "ピン留め解除" to ("Unpin" to "取消置顶"),
    "ピン留め済み" to ("Pinned" to "已置顶"),
    "ピン留めを切り替え" to ("Toggle pin" to "切换置顶"),
    "作品をピン留めして上部に固定" to ("Pin work to the top" to "置顶固定作品"),
    "ピン留めを解除して通常の並び順に戻す" to ("Unpin work and return to normal sort" to "取消置顶并恢复常规排序"),
    "タグ" to ("Tags" to "标签"),
    "タグを編集" to ("Edit tags" to "编辑标签"),
    "作品の分類タグを管理" to ("Manage category tags for this work" to "管理此作品的分类标签"),
    "タグを追加" to ("Add tag" to "添加标签"),
    "新しいタグを入力" to ("Enter new tag" to "输入新标签"),
    "タグ候補" to ("Suggested tags" to "候选标签"),
    "タグが設定されていません" to ("No tags set" to "未设置标签"),
    "設定中のタグ" to ("Current tags" to "已设置标签"),
    "すべて" to ("All" to "全部"),
    "タグで絞り込み" to ("Filter by tag" to "按标签筛选"),
    "タグを削除: %s" to ("Remove tag: %s" to "移除标签：%s"),
    "タグの管理" to ("Manage tags" to "管理标签"),
    "全作品のタグを整理" to ("Organize tags across all works" to "整理所有作品的标签"),
    "%s件の作品で使用中" to ("Used in %s work(s)" to "在 %s 个作品中使用"),
    "登録されているタグはありません" to ("No tags registered" to "未注册标签"),
    "全作品からタグを削除" to ("Delete tag from all works" to "从所有作品中删除标签"),
    "「#%s」をすべての作品から削除しますか？" to ("Delete '#%s' from all works?" to "是否从所有作品中删除“#%s”？")
)
