package com.hikariatelier.app

import com.hikariatelier.app.ui.theme.AppThemeMode

internal data class SettingsUiState(
    val themeMode: AppThemeMode = AppThemeMode.DARK,
    val appLanguage: String = "system",
    val customBackground: Int = 0xFF101014.toInt(),
    val customAccent: Int = 0xFFA8C7FA.toInt(),
    val showStatusBar: Boolean = false,
    val showNavigationBar: Boolean = false,
    val landscapeUseCutout: Boolean = false,
    val manualRotation: Boolean = true,
    val autoRun: Boolean = true,
    val hideEditingPreview: Boolean = true,
    val compactPreview: Boolean = true,
    val preserveExpandedPreview: Boolean = true,
    val landscapePreviewFraction: Float = 0.5f,
    val showResizeHandles: Boolean = true,
    val editorFontSize: Float = 14f,
    val autoIndent: Boolean = true,
    val showLineNumbers: Boolean = true,
    val showEditorAccessoryBar: Boolean = true,
    val codeCompletion: Boolean = true,
    val showAccessoryNavigation: Boolean = true,
    val showAccessorySymbols: Boolean = true,
    val compactAccessoryKeys: Boolean = true,
    val editorWordWrap: Boolean = true,
    val landscapeEditorOnLeft: Boolean = true,
    val draftRecovery: Boolean = true,
    val mp4BitrateMbps: Int = 5,
    val xShareText: String = DEFAULT_X_SHARE_TEXT,
    val recordingCountdownSeconds: Int = 3,
    val shareCardAuthor: String = "",
    val p5Username: String = "",
    val fontLigatures: Boolean = false,
    val customFontFile: String = "",
    val importedFontName: String = "",
    val workSort: String = "更新順",
)
